### ISSUE TITLE
manifest no found

### ISSUE THREAD

**Issue by xrobert35** [jlesage/docker-nginx-proxy-manager#1]
Hello,

i'm getting this error when I try to pull the image from docker hub 

```
docker pull jlesage/nginx-proxy-manager
Using default tag: latest
Error response from daemon: manifest for jlesage/nginx-proxy-manager:latest not found
```
Any idea ?

Thanks

**Comment by jlesage** [comment]
Official `v1.0.0` release now available (along with the `latest` tag).
