### ISSUE TITLE
custom network in unraid wont let me change ports

### ISSUE THREAD

**Issue by sparten9999** [jlesage/docker-nginx-proxy-manager#10]
im using unraid and trying to set nginx proxy manager to the custom network "br0" and when i do it defaults the ports to 4443:4433, 8080:8080, and 8181:8181.
i need it on br0 to give it, its own ip since i need to forward to port 80 and 443.
in the community applications template ill have 80 and 443 listed but when it installs or updates it will always set it to those ports i mentioned earlier.

**Comment by sparten9999** [comment]
actaully looks like a copy of issue 5. i didnt see that post earlier. wish i can change those ports

**Comment by jlesage** [comment]
When using a network mode other than "Bridge", you loose the ability to map ports.  So you need to use the ones of the container (4443, 8080, 8181).

Are you saying that your router can't forward to a different (internal) port?

**Comment by sparten9999** [comment]
im trying to do some dns stuff to push local traffic through to nginx so i can still use nginx if my internet goes out. probably not the right way of doing it but the onyl way i could think of. dns cant do ports so i needed  the docker with it own ip using port 80 and 443.

i was triyng to avoid haivng to make my own dns entries which are basically just repeats of nginx entress

**Comment by jlesage** [comment]
Does your router support NAT reflection?
https://en.wikipedia.org/wiki/Network_address_translation#NAT_hairpinning

**Comment by sparten9999** [comment]
the router is running ddwrt. i dont specifially see anything mentioning it. i can look into it a bit tomorrow though

**Comment by jlesage** [comment]
I think it's called NAT Loopback on ddwrt.
