### ISSUE TITLE
Handing out port on proxy host

### ISSUE THREAD

**Issue by whitlocktech** [jlesage/docker-nginx-proxy-manager#100]
Installed via docker. I changed the port assigned and it started appending the new port to the end of the web address. I removed it and added again with a new valid port but it is still adding the old one to the web address. 
`

server {
  set $forward_scheme http;
  set $server         "192.168.0.55";
  set $port           8122;

  listen 80;

  server_name www.whitlocktech.net;

  access_log /data/logs/proxy_host-27.log proxy;

  location / {

    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
`
If i go the the website is still adds the port. I have flushed my site data on browsers and tried multiple browsers on different machines with the same results.

**Comment by whitlocktech** [comment]
I recreated the Problem again setup a fresh db and a fresh install on a different machine and it does the same thing. It seems to happen when i am using a www subdomain and wordpress as the service hosted.

**Comment by jlesage** [comment]
Sorry not sure to understand the problem.  Which port are you talking about ?
