### ISSUE TITLE
disable logs

### ISSUE THREAD

**Issue by Nuke142** [jlesage/docker-nginx-proxy-manager#105]
How to disable any logs for NPM ?
I have a tons of gigs in /mnt/cache/appdata/NginxProxyManager/log
here i see error.log with
"2020/08/24 13:04:06 [warn] 2546#2546: *907484 an upstream response is buffered to a temporary file /var/tmp/nginx/proxy/2/42/0000000422 while reading upstream ..........."

 and proxy_host-1.log with
"[24/Aug/2020:12:55:29 +0300] - 404 404 - POST http"

 this is because i use custom config with
location ~ /(settings/write|torrent/rem|torrent/restart|shutdown) {
    auth_basic            "Authorization required";
    auth_basic_user_file  /data/access/1;

 so clients see 404 for this pages and this normal. i just need to disable 100 strings per second to logs

**Comment by jlesage** [comment]
You could try to add the following in your custom config:
```
error_log    off;
access_log    off;
```

**Comment by Nuke142** [comment]
access_log    off; - working fine.
error_log    off; - gives "unknown command"

**Comment by jlesage** [comment]
Ok, then `access_log off; ` good enough ?

**Comment by Nuke142** [comment]
yep, it works. thank you.
