### ISSUE TITLE
Unraid Invalid Default Ports

### ISSUE THREAD

**Issue by Jonatino** [jlesage/docker-nginx-proxy-manager#107]
When installing this docker image through Unraid community apps, the default ports are setup as follows:

Web UI: 7818
HTTP Port: 1880
HTTPs Port: 18443

From looking in the nginx files, they seem to always listen on 8080/4443. Shouldn't the default ports be the same?

**Comment by jlesage** [comment]
These the mapped ones.
So:
 - Port 7818 on the host is mapped to port 8181 on the container.
 - Port 1880 on the host is mapped to port 8080 on the container.
 - Port 18443 on the host is mapped to port 4443 on the container.
