### ISSUE TITLE
Update to NPM v2.5.0?

### ISSUE THREAD

**Issue by rclough** [jlesage/docker-nginx-proxy-manager#111]
Hey, thanks for all the work you do maintaining this docker image.

The NPM version of the current `latest` docker image is `v2.3.1`, and since then, a few compelling features have been added in new versions, such as support for cloudflare wildcard DNS certs. I was wondering if you could publish a new image with this version.

Thanks!

**Comment by jlesage** [comment]
Yes I'm working on this.  It's taking a little more time because I want to add additional changes/features, like using g sqlite instead of mariadb to have a lighter container :)

**Comment by rclough** [comment]
Cool! Thanks so much :)

**Comment by ltmichael** [comment]
+1. Wanting to use this but the Cloudflare option is not in v2.3.1. Looking forward to the update!

**Comment by jlesage** [comment]
New image available!
