### ISSUE TITLE
Internal Issue

### ISSUE THREAD

**Issue by carlsimmons81** [jlesage/docker-nginx-proxy-manager#112]
I'm at a loss.  Nginx itself is working just fine via my QNAP using Portainer however I cannot create get Let's Encrypt to work.  Port 80 and 443 are forward to the private IP of the QNAP but still no go.  Do I need an instance of certbot running as well as the script below?

docker run -d \
    --name=nginx-proxy-manager \
    -p 32812:8181 \
    -p 32813:8080 \
    -p 32814:4443 \
    -v /share/Container/nginx \
    jlesage/nginx-proxy-manager

Thanks,

**Comment by jlesage** [comment]
Can you double check with https://canyouseeme.org that port 80 is reachable from the Internet ?

**Comment by carlsimmons81** [comment]
> Can you double check with https://canyouseeme.org that port 80 is reachable from the Internet ?

Hi, yes the port is reachable from the internet.

**Comment by carlsimmons81** [comment]
FYI, I figured out the issue.  QNAP uses port 80 if web services are disabled.  If I enabled web services, I could then change the port from 80 to something else.  Once I did that, 80 free up for nginx.

**Comment by jlesage** [comment]
Great, thanks for the follow up.
