### ISSUE TITLE
Difference between this image and jc21's

### ISSUE THREAD

**Issue by craxrev** [jlesage/docker-nginx-proxy-manager#114]
Great work on this image so far, been using it for so long..

Just wanted to know the main difference between both images.
For instance, I can notice this image is quite small compared to jc21's which is handy sometimes, also the mounted folder structure.. 
apart from those, what is the key difference?

btw I didn't have the chance to use the other image, so maybe that's a reason why I don't know the differences?
anyway, I'm eager to know

**Comment by jlesage** [comment]
The images are mostly the same.  The main differences are that my image has the database integrated.  With the jc21 one, you need to setup it yourself.  Also, mine has nginx running on non-privileged ports and is running under a non-root user.

**Comment by craxrev** [comment]
Thanks! keep it up ;)
