### ISSUE TITLE
docker-compose up -d ERROR

### ISSUE THREAD

**Issue by Freebase394** [jlesage/docker-nginx-proxy-manager#116]
Hi there! 

I Have a dedicated server with Ubuntu18.04LTS - 3cores - 4GB RAM

I have some errors, i can't start the container. 
Shows me the folowing message

> `The Docker Engine you're using is running in swarm mode.

> Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the > > current node.

> To deploy your application across the swarm, use `docker stack deploy`.

> Creating network "npm_default" with the default driver
> ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-> > > 0a614834d368 -j RETURN: iptables: No chain/target/match by that name.
>  (exit status 1))`
![image](https://user-images.githubusercontent.com/19652056/95044493-707e6900-06d7-11eb-8714-7ee0f757c601.png)

Some help Please

**Comment by jlesage** [comment]
Can you share you Docker compose file ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
