### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by pavelbinar** [jlesage/docker-nginx-proxy-manager#12]
Hi,

Is there any way how to change/reset the password without loosing all the configuration?

Thanks.

**Comment by pavelbinar** [comment]
I was temporally able to overcome this issue by using already logged in session.
Create new user, give him admin rights and then delete original user.

However I introduced new problem I was trying to avoid on first place: https://github.com/jlesage/docker-nginx-proxy-manager/issues/13

**Comment by pavelbinar** [comment]
This can be a new feature request

The ability to reset password via email used in registration.

**Comment by jlesage** [comment]
With image version `1.6.0`, you can now reset the password.  See:
https://github.com/jlesage/docker-nginx-proxy-manager#password-reset
