### ISSUE TITLE
localhost or 127.0.0.1 as forwarding destination results in bad request while using ip works

### ISSUE THREAD

**Issue by bayeslearner** [jlesage/docker-nginx-proxy-manager#120]
Just a very simple setup but it doesn't work:

domains:  portainer.bl.net (resolves to 127.0.0.1) 

forwarding:  127.0.0.1 port:9000  

but if I change 127.0.0.1 to the actual IP address then it works.

**Comment by bayeslearner** [comment]
never mind, I know why.  127.0.0.1 or localhost resolves to the docker container itself.

**Comment by nygage** [comment]
> never mind, I know why. 127.0.0.1 or localhost resolves to the docker container itself.

And how do you point to the host? I tried with lan ip but nothing

**Comment by jlesage** [comment]
Is the container configured to use the default bridge network ?
