### ISSUE TITLE
Port 8080

### ISSUE THREAD

**Issue by 82280zx** [jlesage/docker-nginx-proxy-manager#122]
So I have a bit of a problem, I'm hoping there is a way I can resolve this? Also wondering about adding maybe a feature to the stream area?

I'm trying to add this: 

# Unifi STUN UDP Traffic
   upstream unifi_stun {
        server xxx.xxx.xxx.xxx:3478;
   }

   server {
        listen      3478 udp;
        proxy_pass  unifi_stun;
        proxy_responses 1;
        error_log   /var/log/nginx/unifi_stun.log;
   }

# Unifi Inform Traffic

    upstream unifi_inform {
        server xxx.xxx.xxx.xxx:8080;
   }

   server {
       listen      8080;
       proxy_pass  unifi_inform;
       error_log   /var/log/nginx/unifi_inform.log;
   }

I can manually navigate to the stream configs and modify them but the issue is 8080 is in use, I can remap it on Unifi but every time a update comes out it will clear my changes. It would be awesome to see an advanced tab on the stream section like you have in host! Thank you for this awesome program btw!

**Comment by jlesage** [comment]
Could you remap port `8080` on NginxProxyManager instead ?

**Comment by 82280zx** [comment]
Doesn't your guide in here say the ports inside of the docker are mandatory ports / cannot be changed? I might have a work around I'll try, I could probably have it listen on a different port and just pass 8080 from my router to whichever port I map out then have the proxy pass it internally to the correct place (if my brains working right this should work).

**Comment by jlesage** [comment]
The ports used internally by the container can't be changed, but the ones on the host side yes, with the `-p` parameter of the `docker run` command.

**Comment by 82280zx** [comment]
> 
> 
> The ports used internally by the container can't be changed, but the ones on the host side yes, with the `-p` parameter of the `docker run` command.

Thank you! I was able to figure it out, I just routed the port differently, had NGINX listen for the port on a different port and forwarded 8080 to New Port so they wouldn't conflict, seems to have worked.
