### ISSUE TITLE
Nginx Proxy Manager Update

### ISSUE THREAD

**Issue by cmccallu** [jlesage/docker-nginx-proxy-manager#123]
Hi,
     Just wondering if it maybe possible for you to update to the latest Nginx Proxy Manager release?

Thanks
Chris

**Comment by ThomasDK81** [comment]
2.5 is available and it fixes some important bugs.

**Comment by jlesage** [comment]
Done!

**Comment by cmccallu** [comment]
Thanks heaps!

**Comment by cmccallu** [comment]
I may have been a little to eager! While the nginx proxy appears to be working but the manager interface is not

e.g. click SSL Certificates does nothing

[nginx-proxy-manager.html.zip](https://github.com/jlesage/docker-nginx-proxy-manager/files/5436758/nginx-proxy-manager.html.zip)

I've added the log from my synology docker container

**Comment by cmccallu** [comment]
Tried in another browser and all good! Need to clear my browser cache in Chrome! Weird!

**Comment by jlesage** [comment]
Yeah, clearing the browser's cache may be necessary between upgrades.
