### ISSUE TITLE
Database Conversion with Update to v2.6

### ISSUE THREAD

**Issue by chris1668** [jlesage/docker-nginx-proxy-manager#124]
Hello, I noticed the login page had changed to showing v2.6 instead of 2.3 and upon login all I could get to load was a page of the SSL certs, the rest of the web pages dont show anything when clicked. The production json now is refering to a sqlite db with, but doesnt appear to have any credentials for connecting to it. I can Login and View my SSL certs are active, but cant view any other pages from the web ui. My already existing proxy hosts are still proxying and working just not able to manage it from the web ui.
Is this an issue with the db migration or nginx web server?
 {
  "database": {
    "engine": "knex-native",
    "knex": {
      "client": "sqlite3",
      "connection": {
        "filename": "/config/database.sqlite"
      },
      "useNullAsDefault": true
    }
  },

**Comment by jlesage** [comment]
This is probably a caching issue.  Try to clear your browser's cache.

**Comment by chris1668** [comment]
Firefox is not playing nice for some reason now, even tried a fresh install of firefox on another device.
