### ISSUE TITLE
Certbot version conflict

### ISSUE THREAD

**Issue by kuhlivisj** [jlesage/docker-nginx-proxy-manager#127]
When I try to add a proxy host with a ssl certificate I get an Internal error. In the log I see the following message:

`[10/30/2020] [8:42:46 AM] [SSL ] › ✖ error Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation

An unexpected error occurred:

pkg_resources.VersionConflict: (certbot 1.4.0 (/usr/lib/python3.8/site-packages), Requirement.parse('certbot<1.8.0,>=1.7.0'))
Please see the logfile '/tmp/tmpdyxn6kkj/log' for more details.`

After doing a pip install --upgrade certbot on the commandline of the container it is working fine again.

**Comment by jlesage** [comment]
I was not able to reproduce the issue.  Were you creating an SSL certificate with DNS challenge enabled ?

**Comment by kuhlivisj** [comment]
No I didn't use the DNS challenge.
I'm running the container on unraid.

Before the update command version 1.4.0. of certbot was installed. It updated it to version 1.9.0.

**Comment by kuhlivisj** [comment]
Installed the container on an other system to check the version of certbot. It looks you are using an old version of certbot.
Both the version installed via pip as the one installed via apk are version 1.4.0.

Still don't know why I get this error.

Maybe you can update the container to use the latest version of certbot?

**Comment by jlesage** [comment]
Are you able to reproduce the issue on your other system?

Also, I'm wondering which Python package doesn't accept certbot 1.4.0.  Could you grep inside the container:
```
grep -r '1\.8\.0' /usr/lib/python3.8/*
```
```
grep -r '1\.8\.0' /config/.local/*
```
Finally, do you still have access to `/tmp/tmpdyxn6kkj/log`, to get more details about the failure ?

**Comment by kuhlivisj** [comment]
Didn't have time to try it on my other system.

The log file contains the following:
`Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.4.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1317, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 207, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 54, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2461, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2484, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (certbot 1.4.0 (/usr/lib/python3.8/site-packages), Requirement.parse('certbot<1.8.0,>=1.7.0'))
2020-11-07 11:07:41,062:ERROR:certbot._internal.log:An unexpected error occurred:`

The greps returned the following:

`bash-5.0# grep -r '1\.8\.0' /usr/lib/python3.8/*
/usr/lib/python3.8/site-packages/cryptography-2.9.2-py3.8.egg-info/requires.txt:sphinx!=1.8.0,>=1.6.5`

`bash-5.0# grep -r '1\.8\.0' /config/.local/*
/config/.local/lib/python3.8/site-packages/certbot_dns_directadmin-0.0.20-py3.8.egg-info/requires.txt:certbot<1.8.0,>=1.7.0`

**Comment by jlesage** [comment]
Latest certbot version used in latest image.
