### ISSUE TITLE
Issues with chromium edge browser

### ISSUE THREAD

**Issue by combatistor** [jlesage/docker-nginx-proxy-manager#128]
I'm having issues to load the dashboard page and proxy hosts. I'm using Microsoft Edge Version 86.0.622.61 (Official build) (64-bit).
After inspecting the console I get those errors

```
main.bundle.js?v=2.6.1:1 TypeError: Cannot read property 'call' of undefined
    at r (main.bundle.js?v=2.6.1:1)
    at main.bundle.js?v=2.6.1:27
```
```
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at r (main.bundle.js?v=2.6.1:1)
    at main.bundle.js?v=2.6.1:27
```
```
TypeError: n is not a constructor
    at main.bundle.js?v=2.6.1:27
    at main.bundle.js?v=2.6.1:27
```
```
Uncaught (in promise) TypeError: n is not a constructor
    at main.bundle.js?v=2.6.1:27
    at main.bundle.js?v=2.6.1:27
```
It seems it only affect those 2 pages.

This works as intended with google chrome

Any Ideas?

**Comment by jlesage** [comment]
Did you try to clear the browser's cache ?

**Comment by combatistor** [comment]
Oh, never mind, I tried to clear directly the cache as I thought it might be the problem, but doing it quickly I didn't pay attention it was only the last hour cache. 
After checking carefully it was the problem, sorry to bother for that
