### ISSUE TITLE
Lost all configuration, yet redirection works fine

### ISSUE THREAD

**Issue by jazzgott** [jlesage/docker-nginx-proxy-manager#129]
Hi guys, a weird issue here.

I haven't logged on to the proxy manager for a while. 

Today when I tried of course I forgot the username and password, so I tried the default and it worked.
Weird thing is, that the host list is completely empty, yet all the stuff I set up a few months ago is working fine. 
Trouble is, that I am trying to modify my nextcloud redirection and, well, it just isn't there. And it's asking me to change my name/email address, as if it had lost all the configuration. WHICH IS WORKING by the way.

Also, after logging in when I go to the users tab, it looks as if my user was created today.

So the question is:
- Is there any way to list all the users that do not show in the web interface?

**Comment by jlesage** [comment]
Looks like you have multiple instances of the container... You can check with `docker ps`.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
