### ISSUE TITLE
Question - Installation - Data Volumes

### ISSUE THREAD

**Issue by ansred** [jlesage/docker-nginx-proxy-manager#130]
In the 
Data Volumes

It shows only 

Container path | Permissions | Description
-- | -- | --
/config | rw | This is where the application stores its configuration, log and any files needing persistency.

Does that include the cert being generated by Let's encrypt including the uploaded custom cert in the GUI?

If not, what other volumes I need to setup to keep them outside the docker core. I need access to all config/cert/ etc files.

Thanks

My setup is:

Synology Docker

**Comment by jlesage** [comment]
Yes, all required persistent data is saved under `/config` in the container.  No other volume should be needed.
