### ISSUE TITLE
mysqldump no longer in image?

### ISSUE THREAD

**Issue by koffienl** [jlesage/docker-nginx-proxy-manager#133]
I'm running this on q Synology docker setup and did a backup of the internal database with the command ```docker exec nginx-proxy-manager sh -c 'mysqldump -u nginxproxymanager -ppassword123 nginxproxymanager --single-transaction --quick --lock-tables=false > /config/backup/nginxproxymanager-backup.sql' >/dev/null 2>&1```
But since I update the docker to the latest image a few days ago, I get an error telling me mysqldump is no longer there:
```sh: mysqldump: not found```
Do I need a full path to use mysqldump? If so, what is the full path?

**Comment by jlesage** [comment]
With the latest image, mysql is no longer used.  Instead, sqlite is now the used database.  So I guess that if you want to backup the DB, you just need to copy `database.sqlite` (under the folder you mapped to `/config`).

**Comment by koffienl** [comment]
Thanks for quick reply. I was already backing up the entire contents of ```/config``` So that would be enough than :)
