### ISSUE TITLE
Proxying admin port 81 through nginx-proxy-manager with docker network breaks the GUI functionality

### ISSUE THREAD

**Issue by dokbua** [jlesage/docker-nginx-proxy-manager#134]
First step after installing nginx-proxy-manager on a server directly connected to the internet, should be to proxy the unencrypted admin port 81 through the nginx-proxy-manager itself. This can be done through the internal docker network, such as explained for example https://github.com/jc21/nginx-proxy-manager/issues/555 and https://bacnh.com/how-to-setup-nginx-proxy-for-homelab/ . Without this you would have to redirect to the public port and any packet sniffer on the subnet would still be able to read everything going unencrypted from nginx-proxy-manager to the container..

To explain briefly, a internal dedicated docker network is set up, and used to communicate from nginx proxy directly to the internal port of the containers proxied.  It's a very clean and neat solution.  This works fine with all the containers I've tried it with except - ironically - the nginx-proxy manager.  It is possible to login, but the drop-down menus stop functioning correctly.  For example, clicking on the Host menu entry, opens the menu with "Proxy Host" and other settings, but clicking any has no effect. 

Thinking it might be a browser caching issue, I tried through an incognito tab, but it made no difference, so I guess there is some internal logic that needs to be checked.

**Comment by jlesage** [comment]
Which type of network your NginxProxyManager container is using ?  Using the default "bridge" network type, I seems to make it work by creating a new proxy host with the `Forward IP` set to `127.0.0.1` and the `Forward Port` of `8181`.

**Comment by dokbua** [comment]
The network type used is bridge, as created default by the "docker network create" command.  

```
# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
e5529f8abe27        bridge              bridge              local
5747c92f00ad        host                host                local
51f9afd193ab        nginx-network       bridge              local
92bd336b3bce        none                null                local
```

Normally I'd use the container name in the "forward ip" field, but I tried using 127.0.0.1 instead. Unfortunately it made no difference.  The page comes up, but clicking the menu entries have no effect.  

Everything works fine when enabling and going directly to the standard unencrypted admin port 81. I use NPM on other (lan) servers without problems, this is the only server I've tried it on, that is directly connected to the internet.

This forward functionality works correctly to other containers on the same server, it is only a problem going to NPM itself.

**Comment by jlesage** [comment]
On my side, I'm using the default bridge network, not the user-defined bridge network (https://docs.docker.com/network/bridge/).

Did you try with a different browser ?  Also, you could use the browser's developper tools and look at the network tab to see what's going on.

**Comment by dokbua** [comment]
Problem solved. It seems it was a matter of some cache corruption.  I had already tried clearing the browser cache, but didn't notice the time range was set to only 24 hours. Once I reset "all time" it worked. Sorry for wasting your time!
