### ISSUE TITLE
Redirect to Subdirectory Not working - Docker - Synology

### ISSUE THREAD

**Issue by ansred** [jlesage/docker-nginx-proxy-manager#137]
**What is troubling you?**
I am having trouble to point subdomain to the following subdirectory (Windows Server WSUS)

![image](https://user-images.githubusercontent.com/5244872/99158435-c532dd80-26a0-11eb-87c6-ccdf95fb83c3.png)

It's working internally fine, and it's when I expose the port to the internet, but for some reason, Proxy Manager is getting confused to get to it.

btw, @jlesage  you managed to help me once by configuring the advanced settings and it's works for the pi hole setup # https://github.com/jlesage/docker-nginx-proxy-manager/issues/79

`location = /{return 301 $scheme://$http_host/admin;}`

And that worked fine.

However, for the:
http://10.0.12.18:8530/Selfupdate/

![image](https://user-images.githubusercontent.com/5244872/99428898-41156b80-28d5-11eb-8a46-9d28f4f55a32.png)

![image](https://user-images.githubusercontent.com/5244872/99158527-9832fa80-26a1-11eb-8c96-d4f04e469e9d.png)

It doesn't work.

Any advise?

Thanks

**Comment by jlesage** [comment]
I see in your first screenshot that your app is accessed via HTTP, but in the proxy host config you used HTTPs.  Is this an error ?

**Comment by ansred** [comment]
@jlesage sorry about the confusion, it was an old screenshot, I tried both though.

Just updated the screenshot in the main post

The URL work internally fine:
http://10.0.12.18:8530/Selfupdate/

But nothing with the proxy manager host.

Any idea?

**Comment by jlesage** [comment]
What error are you getting exactly ?

**Comment by ansred** [comment]
For some reason, I changed the subdomain to something else and point it to the host and it worked! after restarting the docker 

Something glitchy 

Thanks for brainstorming though!!!
