### ISSUE TITLE
SSL termination not working on docker unraid

### ISSUE THREAD

**Issue by vdhub** [jlesage/docker-nginx-proxy-manager#138]
Hello

I do the settings in the docker container via the interface, I add the proxy hosts and all works perfect when the ssl is disabled, once I enable ssl , even if the certificate is properly generated it does not work anymore. 

Any idea how to fix it and why is not working ? I tried all the possible options for ssl and nothing works . 

I have internal lan servers on http and I need them to be accessible from outside via https , no idea why it does work as http but not as https , and nothing else was done in the interface to break it . 

Thanks in advance.

**Comment by jlesage** [comment]
What error do you have exactly ?  Is port 443 properly forwarded to the container ?

**Comment by vdhub** [comment]
I guess there was some forwarding issue here, is ok now
