### ISSUE TITLE
Portainer Proxy 502 Bad Gateway

### ISSUE THREAD

**Issue by badincite** [jlesage/docker-nginx-proxy-manager#139]
Not sure what's the difference between your version and j21. However yours allowed me to login right away inside portainer when I deployed it so I went with it. Having and issue proxying to other containers I get 502 bad gateway. I was however able to proxy to the portainer interface port. Not sure what I'm missing is there something specific that needs to be setup on the network side? I have both on the default bridged network.

![Networks](https://user-images.githubusercontent.com/7386290/99826074-db6bee00-2b25-11eb-90ac-807d3d9ffb25.PNG)
![ContainerList](https://user-images.githubusercontent.com/7386290/99826075-dc048480-2b25-11eb-88c5-1166c89da375.PNG)
![nginx1](https://user-images.githubusercontent.com/7386290/99826076-dc048480-2b25-11eb-8439-4334b8c4b28e.PNG)

**Comment by badincite** [comment]
Guess this is kind the same as https://github.com/jlesage/docker-nginx-proxy-manager/issues/135

**Comment by badincite** [comment]
Had luck using the internal 172.17.0.xxx IP in place of the VM photon IP.

![4](https://user-images.githubusercontent.com/7386290/99854092-2bf94080-2b52-11eb-83c1-26a8ed5bfb84.PNG)

**Comment by jlesage** [comment]
The error 502 usually means that Nginx Proxy Manager cannot reach the specified IP.  That was probably you issue since changing the IP fixed the problem.
