### ISSUE TITLE
UI Broken after 1.4.0

### ISSUE THREAD

**Issue by rumd3x** [jlesage/docker-nginx-proxy-manager#14]
I was running this image at version 1.4.0.

- Saw there was an update to 1.4.2.
- Recreated my container.
- UI was totally broken (CSS was all wonky, and the only page that actually worked was login and SSL Certificates).
- Tried version 1.4.1 instead.
- UI was still broken.
- Back to 1.4.0.

**Comment by jlesage** [comment]
Did you try to clear your browser's cache?  Or try with another browser?

**Comment by rumd3x** [comment]
Yes I did try clearing cache and even the "Disable cache" option on Chrome developer console. Didn't try on another browser, but I can try that.

**Comment by rumd3x** [comment]
I tried again on Chrome and Edge, and the UI was functional today.. 

But I remember the JS error on the console everytime i clicked anything was something about `prototype extend on null` on the `rocker-loader` file. I couldn't reproduce.

Just the CSS is still wonky.

![screenshot](https://user-images.githubusercontent.com/12579932/57422194-72dc4b00-71e5-11e9-98da-6d4d18a4791d.png)

**Comment by rumd3x** [comment]
Actually, I found some UI elements that are still broken.. I get these two errors for each click.

![error](https://user-images.githubusercontent.com/12579932/57422483-9f449700-71e6-11e9-82e8-451d614b0500.png)

**Comment by jlesage** [comment]
Are you using a 4K display?
An updated docker image will be available today fixing UI issues that occur with big resolution.

**Comment by rumd3x** [comment]
Nope. Just regular 1920x1080 dual monitors. On v1.4.0 it looks normal.

**Comment by rumd3x** [comment]
Gave v1.5.0 a try and it's fixed indeed. I'll close this now.
