### ISSUE TITLE
Question: Custom UID and GUID via docker-compose?

### ISSUE THREAD

**Issue by smokemyshoes** [jlesage/docker-nginx-proxy-manager#140]
Hi

Just a quick question: Is it possible to make the container run off a custom user:group with an environment variable in the docker-compose file similar to below?
`    environment:
      - PUID=XXXX
      - PGID=YYYY`

Thanks in advance!

**Comment by jlesage** [comment]
Yes, by using `USER_ID` and `GROUP_ID`.  See https://github.com/jlesage/docker-nginx-proxy-manager#environment-variables.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
