### ISSUE TITLE
(Fixed) No SSL Certs on Unraid

### ISSUE THREAD

**Issue by TheeMagma** [jlesage/docker-nginx-proxy-manager#141]
Can't create any SSL Certs always get an internal error:

> Error: Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-5" --agree-tos --email "(email)" --preferred-challenges "dns,http" --domains "domain.mmgco.xyz" 
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Plugins selected: Authenticator webroot, Installer None
> Obtaining a new certificate
> Performing the following challenges:
> http-01 challenge for domain.mmgco.xyz
> Using the webroot path /config/letsencrypt-acme-challenge for all unmatched domains.
> Waiting for verification...
> Challenge failed for domain domain.mmgco.xyz
> http-01 challenge for domain.mmgco.xyz
> Cleaning up challenges
> Some challenges have failed.
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Fixed myself. Cloudflare issue. :p

**Comment by jlesage** [comment]
Are you sure Nginx Proxy Manager is reachable over the Internet on port 80 ?

For more details about the failure, you can check at log files in `log/letsencrypt/`, under the folder you mapped to `/config`.
