### ISSUE TITLE
Unraid container port selection

### ISSUE THREAD

**Issue by thatotherguy95** [jlesage/docker-nginx-proxy-manager#142]
Hello, 

I am unsure if this is a bug or expected. But I am trying to set the container port to listen on port 80 and 443. however even after fully deleting the image, appdata and template it still opens the ports to 8080 and 4443. the same thing occurs when using the docker command in the terminal.

Command that was run
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='NginxProxyManager' --net='br0' --ip='192.168.1.94' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'TCP_PORT_8181'='7818' -e 'TCP_PORT_8080'='**80**' -e 'TCP_PORT_4443'='**443**' -e 'USER_ID'='99' -e 'GROUP_ID'='100' -e 'UMASK'='000' -e 'APP_NICENESS'='' -e 'DISABLE_IPV6'='0' -v '/mnt/user/appdata/NginxProxyManager':'/config':'rw' 'jlesage/nginx-proxy-manager'

In Unraid console after successful completion
192.168.1.94:4443/TCP192.168.1.94:4443
192.168.1.94:8080/TCP192.168.1.94:8080
192.168.1.94:8181/TCP192.168.1.94:8181

If there is something obvious I am missing please let me know or if you need any more info I can send it over.

cheers

**Comment by jlesage** [comment]
You need to keep the default "Bridge" network type to be able to change ports.  With any other types, the container's ports (4443, 8080, 8181) are used.

**Comment by Selmaks** [comment]
Is there a way we don't have to use bridge to be able to change the ports?

**Comment by karl007** [comment]
Exact same problem here.. want to run the proxy container with its own IP (net=br0) as a local reserveproxy, to not add for every service running in docker to use (and remember) the port given for the webui. For example `plex.local` instead of `192.168.0.5:10081`.

Is there a way to get this working with this docker image?

**Comment by jlesage** [comment]
Making ports used by the container configurable is not an obvious task.  See https://github.com/jlesage/docker-nginx-proxy-manager/issues/117.

The other solution is to use the Docker image from the original project (https://github.com/jc21/nginx-proxy-manager): this image is using ports 80/443.

**Comment by thatotherguy95** [comment]
Thanks for clarifying that. I did end up going with the original docker image. cheers
