### ISSUE TITLE
Wont Start b/c Address in use

### ISSUE THREAD

**Issue by KillahB33** [jlesage/docker-nginx-proxy-manager#143]
Hi I have watchtower setup to update this and keep having issues after a restart.
I have disabled ipv6 so that error is gone (as the ipv6 address was giving me the same issue) but I am still having the following error.

[nginx] starting...
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address in use)
nginx: [emerg] still could not bind()

**Comment by jlesage** [comment]
Are you using the "host" network mode ?  This indicates that you have something else on your server that is running on port 8080.

**Comment by KillahB33** [comment]
I am not, without any rules the container starts fine it's as soon as I add rules and restart it gives me this error.
I am only exposing port 8080, 8081 and whatever the other port in your compose was.

**Comment by jlesage** [comment]
What are the rules you are talking about ?

If I understand correctly, your Docker compose file maps port 8080 of the host to port 8080 of the container ?

**Comment by KillahB33** [comment]
I am talking about proxy rules, that are pointing to port 8080 on external stuff.

And yes I also have it set to that. 

I have since switched to the official image though so we can close this if you want.

**Comment by jlesage** [comment]
Ok, closing the issue.  Reopen if needed.
