### ISSUE TITLE
Question: what's the advantage of this image over jc21's original image?

### ISSUE THREAD

**Issue by michaelherger** [jlesage/docker-nginx-proxy-manager#144]
Hi @jlesage 

I was wondering what the difference was between your image and @jc21's. Yours is smaller. But feature wise are they identical? Any good reason why I would be using yours?

(Well, I have found one excellent reason: I was having problems getting the original image to run on my Synology. And as @jc21 was pointing at this image wrt. Synology, I gave it a try - and I don't regret it! But I don't understand why I was having those problems to start with.)

Maybe you can add a small section to the readme?

**Comment by jlesage** [comment]
Main differences are:

- The container doesn't use privileged ports.
- The container's processes (including nginx) doesn't run as root.
- Usage of the database is integrated (i.e. no need to manually setup it).
- Automatic rotation of log files.
- Automatic cleanup of Let's Encrypt certificates.

**Comment by michaelherger** [comment]
Thanks for the info! I stuck with your image as getting it to run on DSM was simpler than with the "original" - great job!
