### ISSUE TITLE
Documentation links to nginxproxymanager.com continue to be down

### ISSUE THREAD

**Issue by fiveangle** [jlesage/docker-nginx-proxy-manager#149]
Since it seems this is either being self-hosted on a wholly unreliable connection or otherwise continues to have problems, would it make more sense to use the built-in wiki features of Github for documentation ?

I've been trying to get port-triggering enabled but all roads lead to 404 :)

Thanks for the great project !

**Comment by R0GGER** [comment]
Very strange problem... I can not reproduce your issue.
Do you have some more details about your issue and which steps you took?

**Comment by fiveangle** [comment]
Well, 3 weeks later, the site is back up but it was down each time I checked over the course of a week prior to opening this issue.

Now site is flagged by malware countermeasures: 

![Screenshot 2021-02-11 142846](https://user-images.githubusercontent.com/2219447/107706731-a0391100-6c75-11eb-8373-f00c0de29793.png)

I can only assume it's due to the IP range of the site, which is typical of self-hosted systems.

Anyway, fact remains is the site was down for at least a week so comment above still stands.  I'm not sure the value of the self-hosted site over using the always-on github wiki, but not my project so 🤷‍♂️ 

will close...

**Comment by jlesage** [comment]
I would suggest to report the issue at https://github.com/jc21/nginx-proxy-manager/issues, where the site nginxproxymanager.com is maintained.
