### ISSUE TITLE
SSL generate self signed certified

### ISSUE THREAD

**Issue by nygage** [jlesage/docker-nginx-proxy-manager#150]
Hello, first let me thank you because your image was the unique one works on my Terramaster NAS, after install it I mapped the ports of my router 80 -> 8080 and 443 -> 4443 and both are accesible from the web. I added a SSL certificated issued by Let's Encrypt but when i enter after the generation it says it's self signed. What can be?
In Let's encrypt logs says Congratulations! and it's seems the certificated is well created

Thanks a lot

**Comment by jlesage** [comment]
> I added a SSL certificated issued by Let's Encrypt but when i enter after the generation it says it's self signed.

Not sure to understand what you mean.  You are accessing your proxy host via the domaine name ?

**Comment by nygage** [comment]
> > I added a SSL certificated issued by Let's Encrypt but when i enter after the generation it says it's self signed.
> 
> Not sure to understand what you mean. You are accessing your proxy host via the domaine name ?

It was solved, I've not selected the certificate for the main domain. Now i'm having other issue, if i restart the container it keeps stucked here

> [1/31/2021] [1:07:09 PM] [SSL ] › ℹ info Renewing SSL certs close to expiry...
> --
> 12:07:09 | [1/31/2021] [1:07:09 PM] [IP Ranges] › ℹ info IP Ranges Renewal Timer initialized
> 12:07:09 | [1/31/2021] [1:07:09 PM] [Global ] › ℹ info Backend PID 1182 listening on port 3000 ...
> 12:07:32 | [1/31/2021] [1:07:32 PM] [Nginx ] › ℹ info Reloading Nginx
> 12:07:32 | [1/31/2021] [1:07:32 PM] [SSL ] › ℹ info Renew Complete
> 
> 

What can be?

**Comment by jlesage** [comment]
The following error seems to indicate that the container has issue removing DNS names: 
```
socket.gaierror: [Errno -3] Try again
```

What the following command returns ?
```
docker exec <container name> nslookup r3.o.lencr.org
```

**Comment by nygage** [comment]
> The following error seems to indicate that the container has issue removing DNS names:
> 
> ```
> socket.gaierror: [Errno -3] Try again
> ```
> 
> What the following command returns ?
> 
> ```
> docker exec <container name> nslookup r3.o.lencr.org
> ```

Solved! If it helps anyone the issue is due to a problem with dhcpcd service, check this for more info 
https://forums.docker.com/t/docker-network-changes-ip-after-reboot/103812/4

Thanks!
