### ISSUE TITLE
Internal Error when requesting a new cert

### ISSUE THREAD

**Issue by bignellrp** [jlesage/docker-nginx-proxy-manager#152]
Hi,

Im running this on my Unraid server and everything seems to be working fine apart from creating new SSL certs.
I have moved from having the following flow:

123-Reg --> DDNS --> Firewall --> ISPConfig

to

123-Reg --> CloudFlare --> DDNS --> Firewall --> Nginx Proxy Manager --> ISPConfig

As you can see both the domains work end to end with manual certs uploaded:

https://www.northamptonmorrismen.co.uk
https://www.richardbignell.co.uk

Previously the LetsEncrypt certs were auto renewed from ISPConfig, i now want to renew them from Nginx Proxy Manager.

When i click Create New LetsEncrypt in the GUI i get "Internal Error". So to get this working i imported my certs manually from ISPConfig.

So to review the error i looked in the docker logs.  It says the following command failed:

certbot -vvv certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-15" --agree-tos --email "my@email.com" --preferred-challenges "dns,http" --domains "www.northamptonmorrismen.co.uk"

The following errors were reported by the server:
Domain: www.northamptonmorrismen.co.uk
Type:   unauthorized
Detail: Invalid response

The strange thing is that for one of the domains this worked fine but for all 4 of the rest i get the same error.

I contacted LetsEncrypt and they tried to help but couldnt suggest why it was failing.

Here is the proxy config and the apache config from ISPConfig for the domain failing:

`APACHE CONFIG

DocumentRoot /var/www/clients/client3/web5/web
ServerName northamptonmorrismen.co.uk
ServerAlias www.northamptonmorrismen.co.uk
ErrorLog /var/log/ispconfig/httpd/northamptonmorrismen.co.uk/error.log

NGINX CONFIG

server {
  set $forward_scheme https;
  set $server         "192.168.0.223";
  set $port           443;

  listen 8080;
listen [::]:8080;

listen 4443 ssl http2;
listen [::]:4443;

  server_name www.northamptonmorrismen.co.uk;

  Custom SSL
  ssl_certificate /data/custom_ssl/npm-16/fullchain.pem;
  ssl_certificate_key /data/custom_ssl/npm-16/privkey.pem;

  access_log /config/log/proxy_host-5.log proxy;

  location / {

    Proxy!
    include conf.d/include/proxy.conf;
  }
  Custom
  include /data/nginx/custom/server_proxy[.]conf;
}`

Here is the same config from the domain thats working:

`APACHE CONFIG

DocumentRoot /var/www/clients/client2/web2/web
ServerName richardbignell.co.uk
ServerAlias www.richardbignell.co.uk
ErrorLog /var/log/ispconfig/httpd/richardbignell.co.uk/error.log

NGINX CONFIG

server {
  set $forward_scheme https;
  set $server         "192.168.0.223";
  set $port           443;

  listen 8080;
listen [::]:8080;

listen 4443 ssl http2;
listen [::]:4443;
  server_name www.richardbignell.co.uk;

  Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-5/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-5/privkey.pem;

  access_log /config/log/proxy_host-2.log proxy;
  
  location /ispconfig {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_pass       https://scudvm.richardbignell.co.uk:8080;

  }
  location / {
  
    Force SSL
    include conf.d/include/force-ssl.conf;
    Proxy!
    include conf.d/include/proxy.conf;
  }

  Custom
  include /data/nginx/custom/server_proxy[.]conf;
}`

**Comment by jlesage** [comment]
You can get more details about why the cert fails to be generated by looking at `/mnt/user/appdata/NginxProxyManager/log/letsencrypt`.

**Comment by jlesage** [comment]
Also, Cloudflare interfere with the Letsencrypt process.  Maybe you can share some settings.  For example, do you have proxy enabled ?

**Comment by bignellrp** [comment]
Yes proxy status is "Proxied" and you can see from a dns lookup that the IP is cloudflares IP and shows a cloudflare cert.

SSL is set to FULL: Encrypts end-to-end, using a self signed certificate on the server

**Comment by bignellrp** [comment]
[letsencrypt.txt](https://github.com/jlesage/docker-nginx-proxy-manager/files/5933574/letsencrypt.txt)

Here is the log file for the failed cert

**Comment by jlesage** [comment]
Since Cloudflare is providing the certificate for your domain name, why do you need to generate Letsencrypt certificate in Nginx Proxy Manager ?

**Comment by bignellrp** [comment]
That is a good question.  As cloudflare is set to SSL it is expecting https end to end.  If i do not select a cert in the manager it says HTTP ONLY in the proxy host and cloudflare gives an error 520 even through the end server has SSL and the proxy is forwarding to 443.

All i am trying to achieve is end to end encryption client to server and an easy life where all certs are auto renewed.  If you know how i can configure this maybe i dont need letssncrypt.  Maybe upload a self signed ssl cert that never expires?

**Comment by jlesage** [comment]
If you turn off SSL in Cloudflare, you are still getting end-to-end encryption.  It's just that clients from the Internet connects directly to Nginx Proxy Manager (instead of client -> Cloudflare -> NPM).

Else, like you proposed, uploading/using a custom certificate (i.e. self-signed) in Nginx Proxy Manager should also work.

**Comment by bignellrp** [comment]
Thanks.  I'll go with the self signed for now.
