### ISSUE TITLE
Lets encrypt failed and cannot renew certs 

### ISSUE THREAD

**Issue by vdhub** [jlesage/docker-nginx-proxy-manager#155]
It seems that the last update it failed the lets encrypt part and all the sites now are failed due to that , what can we do to have it fixed ? 

I get this as error and it was working fine before , I just replaced my domains with domain but you will get the idea. 

I tried to delete the old cert to re-generate again , nothing, all failed today and yesterday on renewal process and dead. 

Please I need a solution asap. Thanks in advance. 

Error: Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-20" --agree-tos --email "admin@domain.com" --preferred-challenges "dns,http" --domains "g1.domain.network" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for g1.domain.network
Using the webroot path /config/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain g1.domain.network
http-01 challenge for g1.domain.network
Cleaning up challenges
Some challenges have failed.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by jlesage** [comment]
To get more details about the failure, could you look at `log/letsencrypt/letsencrypt.log`, under the directory you mapped to `/config`?

**Comment by R0GGER** [comment]
Beside DNS or other setup errors, this can also be a firewall issue... For example if you have DNSBL lists enabled in OPNsense or Pfsense.

**Comment by vdhub** [comment]
well it seems that you are right the firewall blocked somehow the letsencrypt server to talk to the servers and that was causing the error so i disabled the firewall and tried again and it worked , now i need to find a way to whitelist those let’s encryption servers

**Comment by R0GGER** [comment]
Nice! I had a simular issue... 

More info: https://community.letsencrypt.org/t/renewal-or-new-issue-behind-a-firewall-fails-due-to-le-operation/135571

> So, the problem is caused by ...
> Examination of HTTP and LE logs following the renewals revealed that:
> 
> - LE has only two servers of its own that issue http-01 challenges (outbound1. and outbound2.letsencrypt.org 1)
> - All other challenges were issued by AWS cloud instances using widely varying IP addresses
> 
> **The great majority of these AWS issued IP addresses appear in DNS blacklists - presumably because their previous users used them to spray out the very sort of traffic nobody wants passing a firewall protecting Internet facing systems.**
