### ISSUE TITLE
Can't change "Settings > Default Site" to anything other than "Congratulations Page" ... SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Jahfry** [jlesage/docker-nginx-proxy-manager#157]
System: Unraid 6.83 (current stable), NPM docker installed yesterday 2/25/2021

Wanted to have hits on unconfigured sites toss 404 errors instead of the Congratulations. 

Went to Settings > Default Site

All options aside from the "Congratulations Page" fail to configure. They do perform some actions (for instance, if I set a custom HTML response the file in appdata/NginxProxyManager/nginix/default_www *is* created). But the server continues to respond with the Congratulations Page. 

Error thrown on client side when submitting anything aside from Congratulations Page is: "SyntaxError: Unexpected end of JSON input". 

![nginx-pm-json-error](https://user-images.githubusercontent.com/16520816/109354540-d4dec800-7832-11eb-812a-26036bc94b24.jpg)

PS. Bonus question: I was wondering if, on a server with some resource limits (old CPU) it would be better for me to try and use the nginx server included in NPM as a basic static web server rather than running a separate additional nginx. Any thoughts?

**Comment by BDeus** [comment]
same for me

**Comment by April-ha** [comment]
me too !!

**Comment by jyourstone** [comment]
Same here

**Comment by jlesage** [comment]
This is fixed with the latest image.

**Comment by April-ha** [comment]
Thank you, everything works fine
