### ISSUE TITLE
Mapping /.well-known for mailserver

### ISSUE THREAD

**Issue by bigjdunham** [jlesage/docker-nginx-proxy-manager#159]
I’m using poste.io as an email server behind npm but I’m having trouble with it generating it’s needed certs. In this document:

https://poste.io/doc/faq

it states I need to “ map /opt/www/.well-known folder to your web server to /.well-known relative path.” But I’m not exactly sure how to do that since I haven’t found .well-known anywhere in the data structure of npm.

Any assistance would be great. Otherwise this is a fantastic app and thanks for building it!

**Comment by jlesage** [comment]
NPM should be used to generate the LetsEncrypt certificate.  So poste.io doesn't need to do it.  Is it something mandatory ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
