### ISSUE TITLE
Connecting to existing proxy host

### ISSUE THREAD

**Issue by ratnose** [jlesage/docker-nginx-proxy-manager#16]
I already got an Nginx proxy setup running with letsencrypt and everything.
I thought this would be a neat way to administrate those domains and such.
But there is no way I can reach the current setup through this.

Maybe I am doing it wrong and I should kill the current setup and do everything through this instead?

**Comment by jlesage** [comment]
Can you provide more details about what is not working?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
