### ISSUE TITLE
Internal error renewing certificate

### ISSUE THREAD

**Issue by maxmonz69** [jlesage/docker-nginx-proxy-manager#160]
HI,
I'm trying to renew Let's Encrypt SSL certificate and I get Internal error.
I saw there are many people experimenting this issue.
Is there a solution?
My nging-proxy-manager is running on a docker container running on a QNAP NAS.
The router has ports 80 and 443 open and mapped to the proxy-manager.

**Comment by jlesage** [comment]
This is usually due to port 80 not being reachable from Internet.  Can you test with https://canyouseeme.org ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
