### ISSUE TITLE
NGX Proxy Manager does not start

### ISSUE THREAD

**Issue by horphi0815** [jlesage/docker-nginx-proxy-manager#168]
Does sombody knows, how to handle this issue?

`nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-8/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-8/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

Best regards,

Phil

**Comment by ricardopaiva** [comment]
Hi,

I'm having this issue as well. Still couldn't figure out how to fix it :|

**Comment by jlesage** [comment]
You could try to run the following command to fix the missing certificate:

```
docker exec <container name> certbot renew --force-renewal
```

**Comment by ricardopaiva** [comment]
Thanks. In the meanwhile I’ve fixed by deleting all data and recreating the containers.
Fortunately it was a recent installation so I fifn’t have a lot of configurations. If i get the error again I’ll it a try.

**Comment by jlesage** [comment]
Ok, thanks for the update.
