### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by fa-ve** [jlesage/docker-nginx-proxy-manager#17]
If I create a https proxy host I get a 504 Gateway Time-out if I request the site. http site's have no issue.

**Comment by jlesage** [comment]
What's the difference exactly between the working and non working config?  Is it that in one case you set a certificate under the SSL tab and in the other you set nothing?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
