### ISSUE TITLE
IP Allow List Limit & Irregularity

### ISSUE THREAD

**Issue by matt-cylanda** [jlesage/docker-nginx-proxy-manager#174]
Hey all,

This has been my favorite and most commonly deployed container I've used anywhere. I started digging into some of the more complex features and was really excited to realize IP filtering is a feature. Unfortunately I discovered it seems we're limited to 4 entries, and it's hit and miss. I have to disable and re-enable a half dozen times before it seems to take effect.

I desperately need this feature implemented, are there any beta's out there that might have an add function available, or a syntax for adding additional IP's on one line?

Thanks,

-Matt

**Comment by jlesage** [comment]
You can add a range of IPs with an entry like this: `192.168.1.0/24`.  Can this work for you ?

**Comment by jlesage** [comment]
Enhancements have been done with the latest version of Nginx Proxy Manager.

Please re-open issue if needed.
