### ISSUE TITLE
No Relevant User Found

### ISSUE THREAD

**Issue by RyanOver9000** [jlesage/docker-nginx-proxy-manager#175]
Describe the bug
I have a new install of NPM. After logging in as admin@example.com / changeme, I set my new login information. If I logout at any point I am unable to log back in with my credentials I have just created.

To Reproduce

Install fresh NPM
Login with admin@example.com / changeme
Change login information
Logout
Try to log back in with newly changed information
Fail
Expected behavior
Log back in to system

Operating System
UnRaid 6.9.1

**Comment by jlesage** [comment]
Just tested with a fresh installation and it's working for me: after logging in with default credentials, I changed the email address to test@example.com and then set a new password.  I then logout and log back with the new credentials successfully.

You can try to run the following command to see which user has been saved to the database:
```
docker exec NginxProxyManager sqlite3 /config/database.sqlite "select * from user"
```

**Comment by Rb0t0** [comment]
Hello I am having this same issue. I tried out your test email test@example.com and I can log out and log back in with that but any time I try to use an email that is mine and try to log back in it comes back as No Relevant User Found. I entered your command as well and the user shows up but no dice on being able to log in

**Comment by BananaHead-ui** [comment]
Hy, so same issue here. Any updates regarding the solution to the problem?

**Comment by jlesage** [comment]
Is there anything special with the email address used ?  If you can, try to reproduce with a fake email address so you can share it here.

**Comment by bagman002** [comment]
I'm having the same issue as described. I'm using a fastmail masked address of blue.sport6700@fastmail.com

I've not yes attempted to rebuild my Docker to test a different email.

**Comment by KagetaneHiruko** [comment]
i found out that the E-Mail is case sensitive and my autofill ruined my login for me...

**Comment by EdgeCon** [comment]
I had the same issue too. I changed the default to Conferr9599@mydomain.com and when I logged out and re-logged back in, I would get "No relevant user found" error.

To resolve the issue, I found out that if I changed the capital "C" in my email address to lowercase "c" (conferr9599@mydomain.com), I would then successfully log in. Strange that the case of my email address didn't save when I set it.

**Comment by jlesage** [comment]
The latest image fixes the issue of email being case sensitive during the login.

I also made a PR for the upstream: https://github.com/NginxProxyManager/nginx-proxy-manager/pull/2638
