### ISSUE TITLE
Is it possible to combine the logs from all proxy hosts?

### ISSUE THREAD

**Issue by HenryKleinschmidt** [jlesage/docker-nginx-proxy-manager#177]
Hello
I don't know if this has been answered but I can't find any info about it. Just like the title says I want to know if its possible that all the log data is written to one log file.

Thanks 
~Henry

**Comment by SimTechLP** [comment]
Hey Henry,

you could try creating a config file under `/config/nginx/custom/server_proxy.conf` and entering the following content:

```
access_log /config/log/access-all.log proxy;
```

The `server_proxy.conf` file should add the access_log line to the end of all proxy server blocks.
Remember to also initially create the file `touch /config/log/access-all.log` and check the file permissions.

Hope that this will solve your problem 😉 

Greetings
~SimTechLP

**Comment by HenryKleinschmidt** [comment]
Thank you! That solved my issue.
