### ISSUE TITLE
port redirection

### ISSUE THREAD

**Issue by FreshImmuc** [jlesage/docker-nginx-proxy-manager#178]
ok so idk it does not happens all the time but sometimes if I try to go to https://domain.com/example-subdirectory/ I get redirected to the Website's port.
for example the apache port is 8080 then I get redirected to https://domain.com:8080/example-subdirectory/

The thing is, that this just happens if I try to reach a Subdirectory. This does not happens if I try to go to a subdomain or the normal Domain.

**Comment by khaivu-mta** [comment]
How do you solve it?

**Comment by FreshImmuc** [comment]
Idk this was very long ago but i think i edited the nginx config to not redirect. And it only did this "error" when i forgot the extra / at the end of the url so is that for you too?

**Comment by khaivu-mta** [comment]
my problem is when i visit a sub url without "/" after such as "https://blog.example.com/my-post" it is redirected to "https://blog.example .com:8080/my -post/". If I add "/" to the end of the url, for example, "https://blog.example.com/my-post/", it points to the right place. The other 8080 port is the port of the service I'm using.

**Comment by FreshImmuc** [comment]
Alright yeah thats exactly what i experienced. I will search for the config code and send it later today!

**Comment by khaivu-mta** [comment]
FreshImmuc, Thank you for your efforts
