### ISSUE TITLE
IPv6 support enabled although 'DISABLE_IPV6=1' in a docker-compose.yml? 

### ISSUE THREAD

**Issue by mibere** [jlesage/docker-nginx-proxy-manager#179]
Hello,

I run v1.14.0 via a _docker-compose.yml_ that contains

```
version: "3"
...
    environment:
      - DISABLE_IPV6=1
```

After the container is running the `docker ps` output also shows IPv6 addresses:

```
... 0.0.0.0:4443->4443/tcp, :::4443->4443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp ...
```

The expected behavior was that IPv6 support is disabled and that there aren't IPv6-addresses waiting for connections.

**Comment by jlesage** [comment]
The `DISABLE_IPV6` environment variable controls behaviour of nginx: the process won't listen on IPv6 and no IPv6 configuration is generated.

What you are seeing in `docker ps` is what Docker setup for the container.
