### ISSUE TITLE
Enable TLS 1.3

### ISSUE THREAD

**Issue by Kraowe** [jlesage/docker-nginx-proxy-manager#18]
How do I enable TLS 1.3?

Support was recently added to jc21/nginx-proxy-manager

https://github.com/jc21/nginx-proxy-manager/issues/128

**Comment by jlesage** [comment]
There is nothing to do, it's enabled by default.  Just make sure you have the latest docker image.

**Comment by Kraowe** [comment]
My sites are still tls 1.2, running the latest docker.

**Comment by jlesage** [comment]
You are right.  The problem seems to be that Nginx in Alpine Linux is build with libressl, which I think doesn't support TLS 1.3 yet.

**Comment by Kraowe** [comment]
But why does jc21/nginx-proxy-manager have support for it, which this docker is built from?

My link above says that "Using the latest version of alpine linux should add nginx and openssl versions that support TLS 1.3"

**Comment by jlesage** [comment]
`jc21/nginx-proxy-manager` is based on debian:

```
# docker run --rm jc21/nginx-proxy-manager cat /etc/debian_version
9.8
```

**Comment by meiskam** [comment]
example of alpine based nginx with tls1.3 support, can this be used? https://github.com/khs1994-docker/nginx-tls1.3/blob/master/alpine/Dockerfile

**Comment by jlesage** [comment]
After some investigation, the problem seems to be related to the fact that the `ssl_protocols` nginx parameter doesn't work at the `server` level when SNI is involved.

**Comment by meiskam** [comment]
If you remove the aNULL cipher from the server block in default.conf, tls1.3 works with SNI
see this fork for a working example: https://github.com/meiskam/docker-nginx-proxy-manager

**Comment by jlesage** [comment]
Thanks for pointers.  Here is an interesting thread discussing the issue: https://www.ruby-forum.com/t/ssl-protocols-per-server/232557

**Comment by jlesage** [comment]
Fixed with the latest image.

**Comment by Kraowe** [comment]
Sorry for opening this again but I updated to the latest image (force update) but it's still only tls 1.3 on my sites. How do I enable 1.3?

**Comment by meiskam** [comment]
Looks like only the config was updated, the nginx and openssl binaries also need updated to include tls1.3.  You can see from my fork 2 months ago I've edited the base image to include an openssl compiled with tls1.3 enabled.
https://github.com/meiskam/nginx-tls1.3

**Comment by jlesage** [comment]
This is hopefully fixed with the latest image.  Tested with www.ssllabs.com.
