### ISSUE TITLE
After flash drive replacement NGINX Proxy Manager not working

### ISSUE THREAD

**Issue by DezzyTee** [jlesage/docker-nginx-proxy-manager#182]
After switching out my boot drive (USB flash drive) for Unraid I am not able to connect to the webui nor do any of the configurations work. 
All I'm getting is "website is not reachable".

**Comment by jlesage** [comment]
You can look at the container's log to see if there is any error.  Also, is the container's configuration the same ?

**Comment by DezzyTee** [comment]
> You can look at the container's log to see if there is any error. Also, is the container's configuration the same ?

Thanks for the advice but I've resolved it by now. I completely forgot to close this thread. 
My solution wasn't pretty but after completely removing any trace of NGINX Proxy Manager and then starting from scratch worked without a hitch. I still don't understand what the problem was but it has been resolved by investing 20 minutes in redoing it.
