### ISSUE TITLE
Update to docker-nginx-proxy-manager 2.9.x

### ISSUE THREAD

**Issue by mmz06** [jlesage/docker-nginx-proxy-manager#185]
Hi There,

Should you update to a more recent nginx-proxy-manager release, to benefit evolutions from it as well, like Let's Encrypt DNS challenge for Duck DNS, I'm missing today ?
https://github.com/jc21/nginx-proxy-manager/releases/tag/v2.9.2 

Thank you !

**Comment by jlesage** [comment]
Yes, I'm working on this today.  I was waiting for 2.9.2 to come out, since other 2.9.x versions had sever issues.

**Comment by jlesage** [comment]
New image available!

**Comment by mmz06** [comment]
@jlesage, Thank you, this is much appreciated !
