### ISSUE TITLE
Cloudflare / 4 Domains 3 ok and 1 Domain Internal Error

### ISSUE THREAD

**Issue by jimthedj65** [jlesage/docker-nginx-proxy-manager#188]
Hi All and many thanks for a great product, helps me to setup up my dev lab very quickly.

I have a weird issue 4 domains and only 1 throws up an internal error, all domains are set up on Cloudflare, my original host was Dreamhost and GoDaddy and I moved them to my dedicated lab server with proxmox.

I check the logs inside the docker by issuing `docker exec -it nginxproxy_app_1 /bin/bash `I then checked the cat /var/log/letsencrypt/letsencrypt.log and found that for this particular domain was throwing the error `acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains:`

All 4 domains were working with existing ssl certs from letsencrypt and I have no idea why this one domain throws up the error, the only difference is my domain was registered on GoDaddy instead of Dreamhost.

Apart from sitting it out is there a way to copy the certificate from Cloudflare/Dreamhost into my docker, I can see the npm files for each domain but I am unsure of the logic with the file naming structure.

any guidance as to what I can do next, if I move the domain back to the original Dreamhost server it works fine.

**Comment by jlesage** [comment]
Your domain seems to be rate-limited by the letsencrypt service.  So waiting a few days and trying again may work.

If you want to find the location of the certificates for your proxy host, you can first find the right config file under `/config/nginx/proxy_host/`.  Once you find it, you will see inside the file `ssl_certificate` and `ssl_certificate_key`, with the path to the certificates.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
