### ISSUE TITLE
Error creating LE Certificate using GoDaddy Dns Challenge

### ISSUE THREAD

**Issue by XenoBIT78** [jlesage/docker-nginx-proxy-manager#189]
I get this error msg when i try to make a Lets encrypt Cert using GoDaddy dns challenge:

/usr/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (urllib3 1.26.4 (/config/.local/lib/python3.8/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
Please see the logfile '/tmp/tmpsqc0vcax/log' for more details.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by m0dd3r43v3r** [comment]
Same Issue as above. On the latest docker image available.

`/usr/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (urllib3 1.26.5 (/config/.local/lib/python3.8/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
Please see the logfile '/tmp/tmpz7vhwul8/log' for more details.`

**Comment by m0dd3r43v3r** [comment]
> I get this error msg when i try to make a Lets encrypt Cert using GoDaddy dns challenge:
> 
> /usr/lib/python3.8/site-packages/requests/**init**.py:89: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
> warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
> An unexpected error occurred:
> pkg_resources.ContextualVersionConflict: (urllib3 1.26.4 (/config/.local/lib/python3.8/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
> Please see the logfile '/tmp/tmpsqc0vcax/log' for more details.
> 
> ```
> at ChildProcess.exithandler (child_process.js:308:12)
> at ChildProcess.emit (events.js:314:20)
> at maybeClose (internal/child_process.js:1022:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
> ```

I was able to connect directly to the Docker container while it was running and upgrade "Requests" which solved this issue for me. At least until I restart the docker container.

`pip3 install --upgrade requests`

**Comment by jlesage** [comment]
I pushed a new image with a fix.  Could you try to see if it fixes your issue ?

**Comment by m0dd3r43v3r** [comment]
I am not getting the error as before once updating but now my challenges are failing. Before the update I created a new cert just fine after running the Requests Upgrade. (_Removed domain name for privacy_)

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-godaddy, Installer None
Performing the following challenges:
dns-01 challenge for test.domain.com
Waiting 30 seconds for DNS changes to propagate
Waiting for verification...
Challenge failed for domain test.domain.com

dns-01 challenge for test.domain.com
Cleaning up challenges
Some challenges have failed.
```

**Comment by jlesage** [comment]
Great, thanks for the follow-up!
