### ISSUE TITLE
nginx + Synology

### ISSUE THREAD

**Issue by hirenshah** [jlesage/docker-nginx-proxy-manager#19]
Apologies in advance as this probably an issue... more so my attempt to get my head around things.

For a few years now I have added my own config to Synology's built-in nginx, and this has been (and still is) working fine.  I like to tinker though and so have set up NPM in Docker on the NAS, which loads up fine.

Questions:
- Is NPM just a manager which "manages" a nginx setup, or does it handle the lot?
- I have 80 and 443 already going to the NAS so moving my config into NPM seems easy enough... would this be a manual thing or can I import it somehow?
- Other than a lovely UI, are there actually any benefits in using NPM?

**Comment by jlesage** [comment]
> * Is NPM just a manager which "manages" a nginx setup, or does it handle the lot?

NPM manages the nginx config and takes care of generating/renewing certificates via letsencrypt.

> * I have 80 and 443 already going to the NAS so moving my config into NPM seems easy enough... would this be a manual thing or can I import it somehow?

You do need to manually convert your config.  Make sure to play with the interface to make sure you can get the same functionality.

> * Other than a lovely UI, are there actually any benefits in using NPM?

NPM is really for people who don't really know nginx but want to securely expose their service.  So if you need complex nginx configuration and are happy with editing configuration files, then it's probably not worth changing to NPM.

**Comment by hirenshah** [comment]
Thanks for the reply.  As per your last point, I think you are right in that there probably isn't much to gain from me exploring this manager.  I am curious though, could it "manage" the Synology built in nginx, or would I have to run a separate nginx in a Docker container alongside?

**Comment by jlesage** [comment]
Yes the container runs its own instance of Nginx.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if required.
