### ISSUE TITLE
IPv6 problems in resolvers.conf 

### ISSUE THREAD

**Issue by tpishere** [jlesage/docker-nginx-proxy-manager#193]
Hello,
I'm running this container on unraid, and use Xiaomi router, the following IPv6 address belongs to the router.
I got the following error:

> nginx: [emerg] invalid IPv6 address in resolver "[fe80::6664:4aff:fe9a:3cb1%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1

**Comment by jlesage** [comment]
Could you provide the output of the following command:
```
docker exec -ti NginxProxyManager cat /etc/resolv.conf
```

**Comment by dragon36** [comment]
I get the same errors. It is fixed by going to the file by console. Then vi resolvers.conf, then remove the %br0 at the end and it fixes it all. Not sure what is adding the %br0 to the end of the IPv6 line. Im running on unriad.

**Comment by tpishere** [comment]
> Could you provide the output of the following command:
> 
> ```
> docker exec -ti NginxProxyManager cat /etc/resolv.conf
> ```

Sorry, I forgot to review this issue for a long time.
The container log shows as follows
`nginx: [emerg] invalid IPv6 address in resolver "[fe80::6664:4aff:fe9a:3cb1%br0]" in /etc/nginx/conf.d/include/resolvers.conf:1`

The following is what resolv.conf contains

root@NAS:~#docker exec -ti NginxProxyManager cat /etc/resolv.conf
# Generated by dhcpcd from br0.dhcp6, br0.ra
nameserver 192.168.0.1
nameserver 223.5.5.5
nameserver 8.8.4.4
nameserver fe80::6664:4aff:fe9a:3cb1%br0

**Comment by jlesage** [comment]
This should be fixed with the latest Docker image.
