### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by qy2009** [jlesage/docker-nginx-proxy-manager#197]
Hi, 

When I tried to run this docker, it seems only supports x86? can it support ARM64? 

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

thanks

**Comment by jlesage** [comment]
Yes, the image currently support only x86.  Other architectures will eventually be supported :)

**Comment by jlesage** [comment]
The latest image is now multi-arch.
