### ISSUE TITLE
I cant create Streams in new version 2.9.8

### ISSUE THREAD

**Issue by capemaxchile** [jlesage/docker-nginx-proxy-manager#204]
I have problems in new version, i update to last image, but now i cant add new Streams, and also have problems when edit olders.
Also, its look bad with destination IP:
![image](https://user-images.githubusercontent.com/45209235/132795971-5a258d59-0a8c-4ac8-9bef-123d8d37c16f.png)

When i press Add Stream, dont work and dont open the window to new stream.

what can i do?

**Comment by jlesage** [comment]
It seems to work for me.  Did you try to clear your browser's cache ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
