### ISSUE TITLE
After updating I am getting permission denied on the binding to 443

### ISSUE THREAD

**Issue by kicker83** [jlesage/docker-nginx-proxy-manager#206]
Hi, 

After updating docker to version 1.21.0 , I can't create any new host, and I can't modify any existing either.

I receive this error:

![image](https://user-images.githubusercontent.com/19304982/133774101-91b5dd4c-eb3c-4dff-a71f-51a75e0576ef.png)

Please, help!

Thanks

**Comment by DanneG** [comment]
Im getting the same error

**Comment by jlesage** [comment]
The container itself doesn't bind to port 443.  How did you created the container ?  Provider the output of `docker inspect <container name>` might also be useful.

**Comment by DanneG** [comment]
> Ok I found the issue. Could you try the latest image ?

v1.21.1 works like a charm thank you!

**Comment by jlesage** [comment]
Thanks for the update!  Closing the issue.
