### ISSUE TITLE
Cannot reset password for user using /opt/nginx-proxy-manager/bin/reset-password

### ISSUE THREAD

**Issue by Tontonjo** [jlesage/docker-nginx-proxy-manager#207]
Hello!

On NPM docker with sqlite db:

After a password loss, i tried to run the reset command as stated in the documentation to reset the password:
https://github.com/jlesage/docker-nginx-proxy-manager#password-reset

Docker command return:
```OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/opt/nginx-proxy-manager/bin/reset-password": stat /opt/nginx-proxy-manager/bin/reset-password: no such file or directory: unknown```

I tried to find this binary in container without luck - Please find this search attached as list.txt
[list.txt](https://github.com/jlesage/docker-nginx-proxy-manager/files/7191667/list.txt)

How can i reset a password then? Has this binary been removed or renamed?

Thanks for your work on NPM and for your help.

Regards - Tonton Jo

**Comment by Tontonjo** [comment]
wrong container :-)

**Comment by douglassllc** [comment]
```
docker exec nginx-proxy-manager /opt/nginx-proxy-manager/bin/reset-password user1
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "/opt/nginx-proxy-manager/bin/reset-password": stat /opt/nginx-proxy-manager/bin/reset-password: no such file or directory: unknown

I also accessed the running container using bash and was unable to find the reset-password script 

```
docker exec -ti nginx-proxy-manager bash
```

```
find / -name reset-password
```

**Comment by jlesage** [comment]
Which Docker image are you using ?

**Comment by douglassllc** [comment]
I found that if I was signed in as `admin`, then it was possible for me to set another users password, without having their original (current) password.

Thanks for responding @jlesage
