### ISSUE TITLE
https Port is unreachable

### ISSUE THREAD

**Issue by thannerfabian** [jlesage/docker-nginx-proxy-manager#214]
I ran my docker container on a complete new ubuntu server with the command:
sudo docker run -d --name=nginx-proxy-manager -p 81:8181 -p 80:8080 -p 443:4443 -v /docker/appdata/nginx-proxy-manager:/config:rw jlesage/nginx-proxy-manager

I can reach Port 80 and 81 but when i call the https-Port i get the error ERR_CONNECTION_REFUSED.
I also tried another browser, disabling all firewall, and a complete reinstallation.

What can the problem be.

Thank you very much in advance.

**Comment by jlesage** [comment]
Are you testing from your internal network?  Do you have a proxy host configured ?

Accessing the management interface (port 8181) should not be a problem, but for ports 8080 and 4443, you can try to reach the proxy host externally to see if it changes anything.

**Comment by thannerfabian** [comment]
Yes, i am in my internal network. Yes, i configured some hosts.

I wanna access the management interface with 81 and it works. Port 80 (http) also works. But 443 doesn't work from internal either from external.

**Comment by thannerfabian** [comment]
Even with your command it doesn't work. The https port is unreachable:
docker run -d \
    --name=nginx-proxy-manager \
    -p 8181:8181 \
    -p 8080:8080 \
    -p 4443:4443 \
    -v /docker/appdata/nginx-proxy-manager:/config:rw \
    jlesage/nginx-proxy-manager

**Comment by jlesage** [comment]
How do you access the HTTPs port ?  Via the proxy host's DNS name ?

Are you saying that you can access the proxy host via port 80, but not via port 443 ?  Maybe you could share your proxy host configuration and the URL you are using to access it ?

**Comment by thannerfabian** [comment]
Yes, i can access it via Port 80 but not 443. I didn´t even set a configuration on the proxy. Its a clean installation. No port (80, 81, 443) is already used or anything.

**Comment by jlesage** [comment]
Ah ok.  If you access NPM on ports 8080 or 4443 without proxy hosts configured, or if accessed via a DNS name not matching a proxy host, you basically end up in a dead-end.

However, accessing a configured proxy host with its DNS name should work fine.

**Comment by thannerfabian** [comment]
i just tried it to access it via the ip of the server. I created a dnsentry and port 80 works with dns name but 443 not.
