### ISSUE TITLE
Another user with Internal error when creating a new cert

### ISSUE THREAD

**Issue by Yonny24** [jlesage/docker-nginx-proxy-manager#218]
Looks like I'm another one with the same issue.

Cannot create the certs.

tried

    -p 81:8181 \
    -p 80:8080 \
    -p 443:4443 \

    -p 8181:8181 \
    -p 8080:8080 \
    -p 4443:4443 \

    -p 81:81 \
    -p 80:80 \
    -p 443:443 \

None of these work I'm afraid.

**Comment by jlesage** [comment]
Is the container accessible from the Internet over port 80 ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
