### ISSUE TITLE
Impossible to start container 

### ISSUE THREAD

**Issue by ohmaxx** [jlesage/docker-nginx-proxy-manager#224]
Hello,

I was refreshing all my certificates on my nginx-proxy-manager docker the first one was ok and then the second get me an error.

So i decide to reboot my docker to see if it was just a little "bug" but now i cant access to my docker webui i have these error in logs : 

[nginx] starting...
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-31/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-31/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

If someone can help me with these :) 

thank you !

**Comment by ch4ox** [comment]
You probably deleted a certificate manually and had still attached the certificate in one of your proxy hosts. After restarting NPM the nginx configuration will still have links to the old cert but these files are now gone and that's what is causing your problem.

I had a similar problem once and I think I resolved it by temporarily copying another set of certificates to the folder where nginx is missing the certs.

Try something like this:
* go to ./letsencrypt/archive/ and hopefully you still have folders there with valid certs.
* temporarily copy one of those folders to the now missing folder npm-31:
* * cd letsencrypt/archive
* * rm -R ../live/npm-31
* * cp [any folder] ../live/npm-31

Try if that temporarily fixes things so you can restart NPM properly.

If you can login to NPM you should immediately find out which of your proxy hosts is npm-31 and unselect/remove SSL from that host. Then delete the temporary folder you copied: rm -R letsencrypt/live/npm-31

Now you should be ready to create a new certificate and attach it back to your proxy host. And remember: Don't delete certificates you still have attached to a proxy host in the future :)

Hope that helps!

**Comment by ohmaxx** [comment]
Hello @ch4ox ! 

Thanks for your asnwer, yes i thinks i have delete a certificate still attached to a proxy host so i will know for the future thanks.

I have try your solution to copy an archive folder into a new npm-31 folder in /live but when i reboot the docker i still have excatly the same message even if i have correctly copy and have the same file as an archive folder.

It's looks like the file in live are a link to the /archive/npm-x/files 
![Capture](https://user-images.githubusercontent.com/59488997/147891653-16a63ea9-75d5-429a-91f9-3d35ed8a56cb.PNG)

But i don't know how to create these link, do you have an idea ?

Thanks for your precious help

**Comment by ch4ox** [comment]
Ah sorry, you're right, the filenames are different. You could just rename those files so they don't have the "1" in their name anymore: mv cert1.pem cert.pem etc.

Another way would be to create those symbolic links but then you'd have to copy the folder in archive and link them manually with ln -s. I would go with the easy method first, so just rename those files :)

**Comment by ohmaxx** [comment]
Thanks a lot for your help !!
![Capture2](https://user-images.githubusercontent.com/59488997/147891978-f5b7d081-a76a-4890-bffa-6680c7f1c3a9.PNG)

I did go the "hard way" with the ln -s config, know it's working again i have access to my gui !

Thanks a lot for your help couldn't have done it without you !

**Comment by zeroggdr** [comment]
> You probably deleted a certificate manually and had still attached the certificate in one of your proxy hosts. After restarting NPM the nginx configuration will still have links to the old cert but these files are now gone and that's what is causing your problem.
> 
> I had a similar problem once and I think I resolved it by temporarily copying another set of certificates to the folder where nginx is missing the certs.
> 
> Try something like this:
> 
> * go to ./letsencrypt/archive/ and hopefully you still have folders there with valid certs.
> * temporarily copy one of those folders to the now missing folder npm-31:
>   cd letsencrypt/archive
>   rm -R ../live/npm-31
>   cp [any folder] ../live/npm-31
> 
> Try if that temporarily fixes things so you can restart NPM properly.
> 
> If you can login to NPM you should immediately find out which of your proxy hosts is npm-31 and unselect/remove SSL from that host. Then delete the temporary folder you copied: rm -R letsencrypt/live/npm-31
> 
> Now you should be ready to create a new certificate and attach it back to your proxy host. And remember: Don't delete certificates you still have attached to a proxy host in the future :)
> 
> Hope that helps!

I was having this same issue and this answer worked for me. Thanks!
