### ISSUE TITLE
DNS Challenge for DuckDns not working

### ISSUE THREAD

**Issue by Rihan9** [jlesage/docker-nginx-proxy-manager#233]
Hi,
when creating a certificate the software raise an error.
It seems to missing some package, because the cffi pip package cannot compile:
`
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.7/c/_cffi_backend.o
      c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
       #include <Python.h>
                ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
`

the cffi package is a dependency for certbot-dns-duckdns~=0.6.

I'm currently use this image: jc21/nginx-proxy-manager:latest updated today on armv7l environment.

**Comment by jlesage** [comment]
Hi, for the jc21 image, you should report issue there:
https://github.com/NginxProxyManager/nginx-proxy-manager/issues

**Comment by sawmilldream** [comment]
Same after a fresh install, after reboot hang system

**Comment by Rihan9** [comment]
I all, I don't see the reason to keep this defect opened. I don't have the same architecture to retest a fix.
