### ISSUE TITLE
Add another certificate issuer

### ISSUE THREAD

**Issue by inowit** [jlesage/docker-nginx-proxy-manager#241]
Hi, I really like the Nginx Proxy Manager project, which simplifies processes. I would like to ask if there is a way to add another certificate provider, such as CESNET PKI, to Nginx Proxy Manager?

Thank you for your response
Jan

**Comment by jlesage** [comment]
You are probably better to use the main project for feature request like this:
https://github.com/NginxProxyManager/nginx-proxy-manager/issues

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
