### ISSUE TITLE
client_max_body_size 10G ;

### ISSUE THREAD

**Issue by meyrj** [jlesage/docker-nginx-proxy-manager#242]
Hi dear , could you please help me , how can find nginx,conf in your counter? i would like to increase "client_max_body_size" to 10G!

**Comment by meyrj** [comment]
I can upload to my host by Nginx  Maximum 100MB in a file by default and i would like to increase to some GB! thanks in advance for help and support .

**Comment by meyrj** [comment]
Solved !  :) 
cd /etc/nginx then vi nginx.conf 
Modified following comment line from 2G to 10G
client_max_body_size          10G;

**Comment by jlesage** [comment]
In the proxy host configuration, you need to use the Advanced tab for this kind of custom configuration.

Else, what you did will be lost at the next Docker image update...

**Comment by meyrj** [comment]
I got it and Thank you dear Jlesage.
