### ISSUE TITLE
Update to Latest Nginx Proxy Manager

### ISSUE THREAD

**Issue by cmccallu** [jlesage/docker-nginx-proxy-manager#254]
Any chance you could update to the newest Nginx Proxy Manager.

**Comment by jlesage** [comment]
Done!

**Comment by cmccallu** [comment]
Thanks heaps for the update!

**Comment by slartibartfass** [comment]
Nginx Proxy Manager **v2.9.19** ist out. Update to new build would be nice.
[https://github.com/NginxProxyManager/nginx-proxy-manager/releases](https://github.com/NginxProxyManager/nginx-proxy-manager/releases)

**Comment by twist3dimages** [comment]
Does this include crowdsec support?

**Comment by slartibartfass** [comment]
@twist3dimages 
https://github.com/LePresidente/docker-nginx-proxy-manager seems to be a fork of [jlesage/nginx-proxy-manager](https://hub.docker.com/r/jlesage/nginx-proxy-manager) with this feature.

**Comment by jlesage** [comment]
I think that crowdsec support has not been merged/added to the upstream yet.
