### ISSUE TITLE
Log rotate for only one Month ?

### ISSUE THREAD

**Issue by masterwishx** [jlesage/docker-nginx-proxy-manager#266]
i have log rotate for only month with autologing from NPM, when used befor manual added for logging in one file it was unlimited i think:  

#NPM Proxy Logs to one file for goaccess monitoring
#access_log /config/logs/proxy_logs.log proxy;
#error_log /config/log/proxy_errors.log warn;

do we have limited foer one moth log rotate ?

**Comment by jlesage** [comment]
Yes, NPM rotates the log files.  There are 4 weeks of access log and 10 weeks of error log.
