### ISSUE TITLE
Build Docker with arm64

### ISSUE THREAD

**Issue by jiatao99** [jlesage/docker-nginx-proxy-manager#272]
Tried to use your docker image in arm CPU however, it does not work. So I cloned the repo and modified Dockerfile with the following:

1. FROM ... changed to alpine:latest
2. Replace all `add-pkg` to `apk add`
3. Replace all `del-pkg` to `apk del`

Run `docker build .` and it built successfully.

Use your docker-compose example to deploy without any issue

However the docker log shows: `No log line matching the '' filter` and nothing happened.

Did I do anything wrong? Is it possible to create a arm image from your side (or maintains a base-image:alpine with arm)? 

I used your docker image for years and love it. 

Thanks for maintaining this great docker image

**Comment by jlesage** [comment]
The latest image is now multi-arch.
