### ISSUE TITLE
Default host certificate leaks implementation information in organization subject (fixed upstream in 2021)

### ISSUE THREAD

**Issue by mlakerveld** [jlesage/docker-nginx-proxy-manager#277]
This has been fixed in nginx-proxy-manager in 2021. Hasn't made it into this repo.

https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1024

Describe the bug
The generated default self signed host certificate leaks implementation name "Nginx Proxy Manager" in the "Organizational" (O) subject field.

To Reproduce

    Browse to default https host
    Review certificate details

Expected behavior
Field should be generic (not reference implementation), like localhost or empty, or definable.

**Comment by jlesage** [comment]
This is fixed with the latest image.
