### ISSUE TITLE
unknown directive "mail"

### ISSUE THREAD

**Issue by KuroSetsuna29** [jlesage/docker-nginx-proxy-manager#281]
Is it possible to enable to mail module? I want to use NPM as a mail proxy server, however I am getting the error `[emerg] unknown directive "mail" in...`.

Eg.
```
mail {
    server_name mail.example.com;
    auth_http   http://127.0.0.1:9000;

    # disabling xclient command
    xclient off;

    server {
        listen     25;
        protocol   smtp;
        smtp_auth  none;
    }
}
```

It looks like it needs to be compiled with the `--with-mail` flag to be able to use the "mail" directive.

**Comment by jlesage** [comment]
Mail module added to the latest image.
