### ISSUE TITLE
Issues after updating to 23.03.01

### ISSUE THREAD

**Issue by rafcio82** [jlesage/docker-nginx-proxy-manager#284]
Hey there,

All the proxy's stopped working after updating to 23.03.01.
I'm running it in the Docker on my Unraid server.

I see no errors starting the docker. 
I got access to backend of NPM. 
I can renew the certificates, create a new one, everything works from that side. 

When I try to access any of the URL configured in it I got a:

Network Protocol Error
An error occurred during a connection to XXXXXX.
The page you are trying to view cannot be shown because an error in the network protocol was detected.
Please contact the website owners to inform them of this problem.

I've got a couple of domains and none of them works.
No other changes than the update was made.
I've tried to restart the container, no change.

Any help would be appriciated.

Thanks

**Comment by Marcel40625** [comment]
same here

**Comment by naelfe** [comment]
Same here.
No problems when accessing nextcloud directly via local IP. Can access nginx gui as well. Same error message trying to access NC via web.
Rolled back to tag [v1.26.1](https://hub.docker.com/layers/jlesage/nginx-proxy-manager/v1.26.1/images/sha256-884cb243f4372cbfcd1d1ee4979b362e9f6126e98feb7d36e121a1b5248a973f?context=explore) and it's working again.

**Comment by rafcio82** [comment]
Rolled back to v1.26.1, and like in naelfe case, it's working again.

**Comment by jlesage** [comment]
I'm looking into this.  I temporarily reverted `latest` tag to `v1.26.1`.

**Comment by jlesage** [comment]
I pushed a new image to fix this issue!
