### ISSUE TITLE
Issues after updating to latest (former 23.03.01)

### ISSUE THREAD

**Issue by naelfe** [jlesage/docker-nginx-proxy-manager#285]
Hello there,
sorry to bother again (coming back to #284 ).

jlesage/nginx-proxy-manager:**v23.03.2** is working now, jlesage/nginx-proxy-manager:**latest** is _not_. I suppose latest is still referencing [v23.03.1](https://hub.docker.com/layers/jlesage/nginx-proxy-manager/v23.03.1/images/sha256-0e0debf910b7c38c1b559f810da3946879626eaa9c4544584ea1c5b64a50fd0c?context=explore) ?

Kind regards

P.S. Thanks for the quick fix yesterday!

**Comment by jlesage** [comment]
`latest` and `v23.03.2` are the same image.  See: https://hub.docker.com/r/jlesage/nginx-proxy-manager/tags

Did you re-pulled the image (`docker pull jlesage/nginx-proxy-manager`) ?

**Comment by naelfe** [comment]
You are indeed correct- was using unraid and changed to tags. When going back from v23.03.2 to latest, it did not pull it again (which it usually does automatically...)
My bad- but thanks a lot!
