### ISSUE TITLE
docker container request

### ISSUE THREAD

**Issue by hans-peter123** [jlesage/docker-nginx-proxy-manager#29]
I'm so sorry to contact you through here, but I found no other way!
Is it possible for you to make a new awesome Docker container for the Sia project?
https://sia.tech/get-started

Like example the jDownloader container, so I can user the GUI through the Webbrowser?
That would be so awesome!
You can delete this message after read :)

**Comment by jlesage** [comment]
Hi,
Thanks for the suggestion.  Can you add it here: http://feathub.com/jlesage/docker-apps
