### ISSUE TITLE
update to npm 2.10.2

### ISSUE THREAD

**Issue by ndaringer** [jlesage/docker-nginx-proxy-manager#290]
I use the docker, any chance this could be updated?

https://www.reddit.com/r/selfhosted/comments/12de7bw/nginx_proxy_manager/ caught my attention.

**Comment by whoshoe** [comment]
Yes, please update it to at least 2.19.22 to mitigate those security issues.

**Comment by zhdenny** [comment]
Anyone know what needs to change to migrate from https://hub.docker.com/r/jlesage/nginx-proxy-manager to https://hub.docker.com/r/jc21/nginx-proxy-manager

https://hub.docker.com/r/jc21/nginx-proxy-manager is at least able to be on latest version that fixes the security issues.

**Comment by serverless83** [comment]
> Yes, please update it to at least 2.19.22 to mitigate those security issues.

The image has been updated to 2.19.22 version 2 days ago, thank you @jlesage

**Comment by ndaringer** [comment]
@serverless83 It is not updated. This is a fresh pull. 
![image](https://user-images.githubusercontent.com/207518/230903586-612d9f10-707e-4fd0-bd3a-bd834bbeb914.png)

**Comment by serverless83** [comment]
> @serverless83 It is not updated. This is a fresh pull. If it had been updated, it would be 2.10.2. ![image](https://user-images.githubusercontent.com/207518/230903586-612d9f10-707e-4fd0-bd3a-bd834bbeb914.png)

Infact, as I said, the version is 2.9.22 that is not affected by the vulnerability.

**Comment by zhdenny** [comment]
I'm confused.....v2.19.22 or v2.9.22. screenshot and what you say show two different things. Are you sure????

v2.19.22 is the version not affected by the vulnerability.

**Comment by serverless83** [comment]
Original message corrected with the right version number.

**Comment by ndaringer** [comment]
There is no v 2.19.22.

**Comment by voodoopt** [comment]
> Anyone know what needs to change to migrate from https://hub.docker.com/r/jlesage/nginx-proxy-manager to https://hub.docker.com/r/jc21/nginx-proxy-manager
> https://hub.docker.com/r/jc21/nginx-proxy-manager is at least able to be on latest version that fixes the security issues.
> Seems there are pretty big port and path changes that are required to migrate but might be MORE. I don't know.
This is my changes

on image: jlesage/nginx-proxy-manager my settings are
    ports:
      - 81:8181
    environment:
      - DB_SQLITE_FILE=database.sqlite
    
on image: jc21/nginx-proxy-manager are
    ports:
      - 81:81
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
     volumes:
      - ./data:/data   # add this volume

**Comment by zhdenny** [comment]
> > Anyone know what needs to change to migrate from https://hub.docker.com/r/jlesage/nginx-proxy-manager to https://hub.docker.com/r/jc21/nginx-proxy-manager
> > https://hub.docker.com/r/jc21/nginx-proxy-manager is at least able to be on latest version that fixes the security issues.
> > Seems there are pretty big port and path changes that are required to migrate but might be MORE. I don't know.
> > This is my changes
> 
> on image: jlesage/nginx-proxy-manager my settings are ports: - 81:8181 environment: - DB_SQLITE_FILE=database.sqlite
> 
> on image: jc21/nginx-proxy-manager are ports: - 81:81 environment: - DB_SQLITE_FILE=/data/database.sqlite volumes: - ./data:/data # add this volume

Have you tested this migration yourself?

**Comment by voodoopt** [comment]
> > > Anyone know what needs to change to migrate from https://hub.docker.com/r/jlesage/nginx-proxy-manager to https://hub.docker.com/r/jc21/nginx-proxy-manager
> > > https://hub.docker.com/r/jc21/nginx-proxy-manager is at least able to be on latest version that fixes the security issues.
> > > Seems there are pretty big port and path changes that are required to migrate but might be MORE. I don't know.
> > > This is my changes
> > 
> > 
> > on image: jlesage/nginx-proxy-manager my settings are ports: - 81:8181 environment: - DB_SQLITE_FILE=database.sqlite
> > on image: jc21/nginx-proxy-manager are ports: - 81:81 environment: - DB_SQLITE_FILE=/data/database.sqlite volumes: - ./data:/data # add this volume
> 
> Have you tested this migration yourself?

yes ;)

**Comment by jlesage** [comment]
Closing this issue, version 2.10.4 integrated a while ago.
