### ISSUE TITLE
[Bug?] Http2 enabled but origin server logs showing http1.1

### ISSUE THREAD

**Issue by donniewr** [jlesage/docker-nginx-proxy-manager#305]
### Current Behavior

Hello,

I'm not sure if that's a bug, I enabled HTTP2 and force HTTPS but on my origin server the access logs are saying http1.1.

Http2 only work between the browser and Nginx Proxy Manager? No http2 between NPM and the origin server?

My origin server supports HTTP2 and redirect to HTTPS.

Thanks.

### Environment

- OS: Ubuntu 
- OS version:22.04
- Docker version: Latest

### Container creation

docker-compose.yml
docker-compose up -d

### Container log

```text
?
```

**Comment by jlesage** [comment]
Correct, this option enables support of HTTP2 in the Nginx server (thus for clients connecting to NPM).
