### ISSUE TITLE
[Bug]  Using uninitialized "test" variable, client: x.x.x.x, server: my.doamins.com requests ...

### ISSUE THREAD

**Issue by masterwishx** [jlesage/docker-nginx-proxy-manager#314]
### Current Behavior

using lasted version in Docker in Unraid  + Authelia+Cloudflare .
After last update have a lot of warnings For Every Proxy hosts:

```[warn] 464#464: *60 using uninitialized "test" variable, client: 162.158.x.x, server: sub.mysite.com, request: "GET /api/sync HTTP/2.0", host: "sub.mysite.com"```

and also vaultwarden have this :  

  ``` an upstream response is buffered to a temporary file /var/tmp/nginx/proxy/2/35/0000001352 while reading upstream, client: x.x.x.x, server: sub.mysite.com, request: "GET /api/sync HTTP/2.0", upstream: "http://192.168.0.199:4743/api/sync", host: "sub.mysite.com"```

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

Docker in Unraid

### Container log

```text
..
```

**Comment by jlesage** [comment]
> [warn] 464#464: *60 using uninitialized "test" variable, client: 162.158.x.x, server: sub.mysite.com, request: "GET /api/sync HTTP/2.0", host: "sub.mysite.com"

Ok I will push a fix for this.

>    an upstream response is buffered to a temporary file /var/tmp/nginx/proxy/2/35/0000001352 while reading upstream, client: x.x.x.x, server: sub.mysite.com, request: "GET /api/sync HTTP/2.0", upstream: "http://192.168.0.199:4743/api/sync", host: "sub.mysite.com"

I think this should not cause any issue.  Do you see any problem accessing your service ?

**Comment by masterwishx** [comment]
> I think this should not cause any issue. Do you see any problem accessing your service ?

all hosts are working, there was problem with sync on vaultwarden, it was his issue, after exited from extensions it's working fine, and still have this warning.

Also can find 'test' variable in hosts advanced settings.

**Comment by masterwishx** [comment]
Thanks, working fine
