### ISSUE TITLE
PASSWORD RESET

### ISSUE THREAD

**Issue by sun-bear** [jlesage/docker-nginx-proxy-manager#34]
Hello, something happened with my password manager and it did not correctly save the password for the email/password login that I created for my nginx setup (for the browser configuration site). Is there any way I can recover my password without having to rebuild the docker from scratch?

Any help is much appreciated.

**Comment by Unthred** [comment]
I have a similar issue. After creating access lists I can no longer login. I dont understand what I have done wrong. Is there any way to reset the password?

**Comment by jlesage** [comment]
I'm working on a solution for this...

**Comment by jlesage** [comment]
With image version `1.6.0`, you can now reset the password.  See:
https://github.com/jlesage/docker-nginx-proxy-manager#password-reset

**Comment by Unthred** [comment]
Awesome thanks!
