### ISSUE TITLE
Feature: Arm architecture

### ISSUE THREAD

**Issue by Bockiii** [jlesage/docker-nginx-proxy-manager#36]
Hi,

I love the docker, thanks for providing it!

I see that the dev of this (jc21) as an arm version of the docker. Would you be able to provide that as well?

I like the all-in-one-approach from your docker better than his :)

Thanks!

PS: Someone requested the inclusion of nginxproxymanager in this: 

https://github.com/GhostWriters/DockSTARTer 

so I added yours instead of jc21s. That's why I'm asking about arm :)

**Comment by rgulden** [comment]
Ohh many i would love armfh support :)

**Comment by funker** [comment]
Ah, OK. This seems to be the problem I run into. +1 for an arm version :-)

I always get the following message when trying do docker-compose up on a Raspberry 2.
`standard_init_linux.go:211: exec user process caused "exec format error"`

Any news on that topic?

**Comment by JaneTrix** [comment]
Would also like to see this supporting ODROID HC2

**Comment by mouseron** [comment]
Just wondering where this is up to please? I prefer your PUID and PGID implementation over jc21's. Is it possible to run this on a raspberry pi with arm/v7?

**Comment by mouseron** [comment]
> To support arm, I also need to have compatible baseimages... This will eventually come :)

Just wondering where this is up to please? I prefer your PUID and PGID implementation over jc21's. Is it possible to run this on a raspberry pi with arm/v7 yet?

Thanks!

**Comment by my-flow** [comment]
+1

**Comment by cutzenfriend** [comment]
+1000

**Comment by jlesage** [comment]
The latest image is now multi-arch.
