### ISSUE TITLE
Can't generate SSL certificate

### ISSUE THREAD

**Issue by Ulisses1478** [jlesage/docker-nginx-proxy-manager#39]
Failed authorization procedure. xxxxxx.xxx (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://xxxxxx.xxx/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx: Timeout during connect (likely firewall problem)

Doesn't matter if it is a fresh install or if it is an old one. I always get this error.
And yes my ports are OPEN and not filtered at all.

**Comment by jlesage** [comment]
The container doesn't seem to be reachable from the internet on port 80.

Check on https://www.yougetsignal.com/tools/open-ports/ if port 80 is reported as open.

**Comment by Ulisses1478** [comment]
The site you send me report as closed but I can access the reverse proxy only with http

**Comment by Ulisses1478** [comment]
nmap:
PORT   STATE SERVICE
80/tcp open  http

**Comment by jlesage** [comment]
Are you testing outside your network?  Port 80 may be reachable from inside your network, but not from the outside.

**Comment by Ulisses1478** [comment]
It was it, im closing
