### ISSUE TITLE
unraid error Migration table is already locked

### ISSUE THREAD

**Issue by Jagsta2121** [jlesage/docker-nginx-proxy-manager#4]
i have an error when i try to start the proxy manager in unraid. it gives me: error Migration table is already locked. info Current database version: 20181019052346. Can't take lock to run migrations: Migration table is already locked
If you are sure migrations are not running you can release the lock manually by deleting all the rows from migrations lock table: migrations_lock.
it worked fine until i restarted the server. how do i go about fixing this? i dont have mariadb installed in docker.

**Comment by jlesage** [comment]
Hi,
Can you please provide the whole container log?
Thanks!

**Comment by Jagsta2121** [comment]
> Hi,
> Can you please provide the whole container log?
> Thanks!

https://pastebin.com/eTf1supx

**Comment by jlesage** [comment]
Can you please try the latest image?  It should fix the issue.

**Comment by jlesage** [comment]
Closing the issue.  Please reopen if needed.
