### ISSUE TITLE
Forcing SSL creates too many redirects

### ISSUE THREAD

**Issue by SilentMonarc** [jlesage/docker-nginx-proxy-manager#43]
Turning on the option "Force SSL" causes too many redirects.

Without force on, the site works in both HTTP, and HTTPS

This is the generated config file: https://pastebin.com/dft7kLq5

**Comment by jlesage** [comment]
You can use the browser's developper tool to see the redirects that are happening.
Is the issue occurs from both the inside and the outside of your network?
Also, make sure your DNS provider doesn't do some redirection itself.

**Comment by SilentMonarc** [comment]
Thank you, that was it.
The DNS provider was trying to do some redirection.

Thanks
