### ISSUE TITLE
How to setup in Google cloud VM?

### ISSUE THREAD

**Issue by JohnnyPicnic** [jlesage/docker-nginx-proxy-manager#44]
I have the manager running with port 80 and 443 open in my firewall.
I have added a proxy host for a duckdns.org subdomain and i'm trying to get a certificate for my self hosted bitwardenrs site.
I can't seem to figure out the proper configuration for the proxy host. The error I get is:
`Failed authorization procedure. bwcloud.duckdns.org (http-01): urn:ietf:params:acme:error:connection :: The server 
could not connect to the client to verify the domain :: Fetching http://*******.duckdns.org/.well-known/acme-challe
nge/c8Ero5fXAJ-D2vV-NzfxpSptjG7MWITxVg9oq0gVIe0: Connection refused`

I'm using the manager from my home assistant server and it works great. Thought I would try it in a cloud VM but I'm just a newb...

**Comment by jlesage** [comment]
So the error you got is when NPM is running in the cloud ?

The error message indicate that NPM can't be reached through port 80 from the internet...

**Comment by JohnnyPicnic** [comment]
Thanks, it was a firewall issue.
