### ISSUE TITLE
Container uses wrong resolv.conf

### ISSUE THREAD

**Issue by vipergts450** [jlesage/docker-nginx-proxy-manager#45]
Is there a way to have this container use docker's built in bridge network's resolv.conf rather than the host's? I am having an issue resolving the names of other containers because /etc/resolv.conf points to the host's nameservers instead of using Docker's.

**Comment by jlesage** [comment]
This seems to be a limitation of docker:

> Containers on the default bridge network can only access each other by IP addresses, unless you use the --link option, which is considered legacy. 

https://docs.docker.com/network/bridge/

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
