### ISSUE TITLE
Stub file

### ISSUE THREAD

**Issue by modem7** [jlesage/docker-nginx-proxy-manager#47]
Does this image have the stub file enabled at all?

https://nginx.org/en/docs/http/ngx_http_stub_status_module.html

If not, would it be possible to have it enabled?

This would enable people to gather stats via netdata etc

Many thanks!

**Comment by modem7** [comment]
This would enable people to gather stats via netdata etc

**Comment by Shifter2600** [comment]
Found a way
https://github.com/jlesage/docker-nginx-proxy-manager/issues/69

**Comment by modem7** [comment]
Have moved to Traefik, will close issue unless someone else requires this functionality.
