### ISSUE TITLE
Port redirection

### ISSUE THREAD

**Issue by vibratim** [jlesage/docker-nginx-proxy-manager#5]
Hello,

I just wanted to ask if it is possible to use the default ports from the orignial docker container (80,81,443).
I am running in some issues now with the use of unraids new br0 network and this container. My NginxProxyManager is getting it's own IP so I am not able to redirect the ports any longer. So port 8080, 8181 and 4443 are published by the container.

Best Regards :)

**Comment by jlesage** [comment]
The reasoning behind **not** using privileged ports 80,81 and 443 is that it allows the container to runs as non-root.

Is there any reason why you need the container to have its own IP?

**Comment by vibratim** [comment]
Ok but nevertheless there isn't an option to use the privileged ports ?

**Comment by jlesage** [comment]
Currently the ports are hard-coded into the container.

However, if you use the standard "Bridge" network mode, you can map container's ports to privileged host's ports (e.g. map port 80 on the host to port 8080 of the container).
