### ISSUE TITLE
ACME v1 deprecated in june

### ISSUE THREAD

**Issue by Benigans** [jlesage/docker-nginx-proxy-manager#53]
Hi !
I received an email informing me that one or more of my domains were issued or renewed using acme v1 :

> According to our records, the software client you're using to get Let's
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
in the past two weeks using the ACMEv1 protocol. Here are the details of one
recent ACMEv1 request from each of your account(s)
...
Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail.

By the time I received this email I was not running the latest version of NPM so I upgraded but can't find if anything changed about the acme version used.

Do you have any info about that ?
Thanks !

**Comment by RickoT** [comment]
I also have interest in this, I would love to continue using this product but if letsencrypt won't work once acmev1 is phased out I'll have to find something new

Please update!
:D
Thanks!
~Rick

**Comment by jlesage** [comment]
I don't seem to have this issue.  Can you look the messages at `log/letsencrypt/letsencrypt.log`, under the directory you mapped to `/config`, and see where the requests are sent?  You should see something like :
```
2020-03-11 05:06:14,439:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/3293961697/wUalfw:
```
The URL in this message shows that `acme-v02` is used.

**Comment by Benigans** [comment]
I looked in the log and found that for a cert I issued last week :
`2020-03-05 10:42:39,019:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-cert:
`
It's joining acme-v01...strange. 
I'll try to re-install the latest version without the saved config to see if it's joining acme-v02 instead of acme-v01.

**Comment by Benigans** [comment]
> 
> 
> I looked in the log and found that for a cert I issued last week :
> `2020-03-05 10:42:39,019:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-cert:`
> 
> It's joining acme-v01...strange.
> I'll try to re-install the latest version without the saved config to see if it's joining acme-v02 instead of acme-v01.

Ok so, I looked the logs on a other proxy I re-installed last month (with the same problem).
I found on the logs :
`2020-02-02 18:11:44,325:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/2607937810:`

This installation use acme v2 now (was using acmev1 before).

I'll reinstall the other proxy. It has to be the fact that I use an older version. Don't know why but it's working now.

Thx !

**Comment by jlesage** [comment]
Great!  Please re-open the issue if needed.
