### ISSUE TITLE
[Question] How to use with many ports with one domain?

### ISSUE THREAD

**Issue by RomanXT** [jlesage/docker-nginx-proxy-manager#54]
I also have a problem with port forwarding.
Example:
http://192.168.0.150:5800 at https://exmaple.com:5800
http://192.168.0.150:9200 at https://exmaple.com:9200
http://192.168.0.150:9400 at https://exmaple.com:9400
I do not know how to do this??

I cannot make a subdomain

**Comment by mandatoryoption** [comment]
Why bother with the reverse proxy then? just forward at the router to that target.

**Comment by RomanXT** [comment]
Maybe I spoke wrong

Enter the webiste https://example.com5800 the connect docker http://192.168.0.150:5800
Enter the webiste https://example.com9200 the connect docker http://192.168.0.150:9200
it doesn't work because the proxy only provides access on one port 443

**Comment by mandatoryoption** [comment]
Right, but whats the point of using a reverse proxy if you cant use subdomains and must use ports? You can just forward the ports on the router directly to 192.168.0.150

I don't think nginx can do what you're looking to do but you might be able to set up a reverse proxy by path. Instead of using example.com:5800 you can do example.com/5800 but I dont think this containers web interface supports that kind of configuration, or if it does I don't know how to implement it via the web interface.

**Comment by RomanXT** [comment]
With HTTP the redirection to host works normally but my point is that it works after HTTPS with Lets Encrypt

**Comment by jlesage** [comment]
This container may not be the right option for what you try to achieve.  I guess the main feature you are looking for is the management of SSL certificates?

With this container, all your services are accessed through a single point (IP/port).  As @mandatoryoption mentioned, you can try to use "Custom Locations" in NPM to access you services under a specific URL path.

Else, there are many DNS services that allow you to have subdomain DNS names for free (e.g. duckDNS).

**Comment by RomanXT** [comment]
I tried different settings in "Custom Locations" with great failure.
I solved the problem differently, a separate proxy container for each container.
Ok, thanks for help

**Comment by RomanXT** [comment]
I have another question how one Nginx-proxy-manager application can use Lets Encrypt certificates on the other Nginx-proxy-manager, on the same host?

**Comment by jlesage** [comment]
It's not really possible, since NPM is generating the certs and has no functionality to share its config across multiple instances.
