### ISSUE TITLE
Forcing SSL creates too many redirects error.

### ISSUE THREAD

**Issue by Landelor** [jlesage/docker-nginx-proxy-manager#6]
Hi,

Whenever I enable the force SSL option I get "Too many redirects errors".

Regards,

**Comment by jlesage** [comment]
What is your proxy host config?  Does it work if you manually access the configured forward host?
You may use the developer tools of the browser to see which redirections are occurring.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
