### ISSUE TITLE
Error when starting docker container

### ISSUE THREAD

**Issue by BenHall-1** [jlesage/docker-nginx-proxy-manager#65]
Hey, I get this error when trying to boot up the docker container:
`nginx: [emerg] bind() to [::]:80 failed (13: Permission denied)`

**Comment by jlesage** [comment]
This is now fixed with the latest image.

To fix the offline proxy hosts, just edit them and save.

**Comment by BenHall-1** [comment]
Okay, I'll test it now

**Comment by BenHall-1** [comment]
Just pulled the latest image, still getting the error...

**Comment by BenHall-1** [comment]
![image](https://user-images.githubusercontent.com/15686484/78834603-c2735a00-79e6-11ea-8855-018d972ff41b.png)
![image](https://user-images.githubusercontent.com/15686484/78834653-d454fd00-79e6-11ea-9dad-96a27039cb1d.png)

**Comment by jlesage** [comment]
Did you edit re-saved your offline proxy hosts ?

**Comment by BenHall-1** [comment]
I can't get into the manager to even edit them :/

**Comment by jlesage** [comment]
Then look in files under `nginx/proxy_host/` (under the directory you mapped to `/config`) and make sure there is no listen on ports 80 and 443:

`listen 80;` -> `listen 8080;`
`listen [::]:80;` -> `listen [::]:8080;`
`listen 443 ssl http2` -> `listen 4443 ssl http2`
`listen [::]:443` -> `listen [::]:4443`

**Comment by BenHall-1** [comment]
That fixed it, thank you so much
