### ISSUE TITLE
Container Fails to Start on Raspberry Pi

### ISSUE THREAD

**Issue by neil-bowers** [jlesage/docker-nginx-proxy-manager#7]
Upon startup, the container fails and exits with the following message:

`standard_init_linux.go:207: exec user process caused "exec format error",`

That would seem to indicate that one of the binaries in use isn't correct for the Raspberry Pi's `armhf` CPU, but looking through the Docker file I don't see anything out of the ordinary or referencing a specific architecture that I would need to change before deploying the container.

Any ideas?

**Comment by jlesage** [comment]
Currently, the image on Dockerhub is for x86_64 platforms only.
