### ISSUE TITLE
Cannot access proxy host webgui

### ISSUE THREAD

**Issue by mjone4** [jlesage/docker-nginx-proxy-manager#70]
I am having issues navigating to the proxy host webgui page.  All other pages seem to open correctly.      http://ipaddress:port/nginx/proxy doesn't load or do anything.  Any guidance would be greatly appreciated!  Thanks!

**Comment by mjone4** [comment]
not sure what happened but its working now... closing issue

**Comment by Tmargo101** [comment]
I also am having this issue.

**Comment by jlesage** [comment]
Which browser are you using ?  Did you try a different browser or clear the cache ?
