### ISSUE TITLE
nginx-proxy-manager.sh error code 1 on database init 

### ISSUE THREAD

**Issue by alucarddelta** [jlesage/docker-nginx-proxy-manager#77]
On Container create, nginx-proxy-manager.sh errors out with exit code 1, causing the container to stop.  The logs looks like it is complaining about free space, but the drive have 2.7TB free.  Thinking it was a permission issue I have tried both 1000:1000 and 0:0.

> [cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] nginx-proxy-manager.sh: executing... 
[cont-init.d] nginx-proxy-manager.sh: Initializing database data directory...
[cont-init.d] nginx-proxy-manager.sh: exited 1.
[services.d] stopping services
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

The only changes I made compared to the Dockerfile, is the volume path on the host, and the port on the host (8080 was already in use)

>acnologia:/tank_0/docker/appdata# cat proxy-manager/log/init_db.log 
Installing MariaDB/MySQL system tables in '/config/mysql' ...
2020-05-10 12:27:42 0 [ERROR] InnoDB: preallocating 12582912 bytes for file ./ibdata1 failed with error 95
2020-05-10 12:27:42 0 [ERROR] InnoDB: Could not set the file size of './ibdata1'. Probably out of disk space
2020-05-10 12:27:42 0 [ERROR] InnoDB: Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
2020-05-10 12:27:43 0 [ERROR] Plugin 'InnoDB' init function returned error.
2020-05-10 12:27:43 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2020-05-10 12:27:43 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2020-05-10 12:27:43 0 [ERROR] Aborting
Installation of system tables failed!  Examine the logs in
/config/mysql for more information.
The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:
    shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
You can also try to start the mysqld daemon with:
    shell> /usr/bin/mysqld --skip-grant-tables --general-log &
and use the command line tool /usr/bin/mysql
to connect to the mysql database and look at the grant tables:
    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;
Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /config/mysql that may be helpful.
The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss
Please check all of the above before submitting a bug report
at http://mariadb.org/jira

**Comment by jlesage** [comment]
This error usually occurs on a file system that doesn't support fallocate system call.
On which filesystem `/config` is mapped ?

**Comment by alucarddelta** [comment]
The ZFS is being used.

**Comment by jlesage** [comment]
`fallocate` is not supported on ZFS... :(

**Comment by alucarddelta** [comment]
If I was to mount the directory on an external drive with a `EXT4` FS. would /config suffice?

**Comment by jlesage** [comment]
Yes, if `/config` is mapped to a filesystem supporting `fallocate` (like `ext4`), it should work.

**Comment by H4R0** [comment]
I was having the same issue, using official mariadb container "mariadb:10.5.4" works on zfs. I used it in combination with the jc21 image "jc21/nginx-proxy-manager"

**Comment by alucarddelta** [comment]
Resolved with work EXT4 workaround

**Comment by jlesage** [comment]
Note that this issue is no longer relevant with recent versions on the image, which use sqlite instead of mariadb.
