### ISSUE TITLE
Issue with one docker host

### ISSUE THREAD

**Issue by ansred** [jlesage/docker-nginx-proxy-manager#79]
Greetings,

First, thanks for this amazing tool, it makes out lives easier indeed.

I have an issue with one docker container "Pihole" where it's not being directed as it should be.

Local URL: [http://10.0.3.16:85/admin](url)

It only works with the hostname/ FQDN, but not URL+Folders as above

<img width="1462" alt="Screenshot 2020-05-24 08 39 23" src="https://user-images.githubusercontent.com/5244872/82754475-1a99cc00-9d9b-11ea-8dee-5b211d228d6f.png">

So when I hit [http://pi.ans.red](url) >> it works, but I have to enter /admin manually and that will revoke the certificate.

<img width="1447" alt="Screenshot 2020-05-24 08 42 10" src="https://user-images.githubusercontent.com/5244872/82754483-271e2480-9d9b-11ea-9d8c-4ef940ffaaa8.png">

I have tried to use both Proxy Hosts and Redirection Hosts, none worked.

Please let me know if you could help.

Thanks,
Anas

**Comment by jlesage** [comment]
Try to add the following under the Advanced tab:
```
location = /{return 301 $scheme://$http_host/admin;}
```

**Comment by ansred** [comment]
@jlesage you are a life saver sir! That did the trick!!! It worked, with that custom line.

Any idea if it's possible to maintain the certificate though, when it goes to the URL?

Screenshot.

<img width="711" alt="Screenshot 2020-05-24 15 35 48" src="https://user-images.githubusercontent.com/5244872/82763263-6452d880-9dd4-11ea-9e07-184a67314185.png">

Thanks

**Comment by jlesage** [comment]
How did you configured the proxy host ?

**Comment by ansred** [comment]
> How did you configured the proxy host ?

That was a good question, I have noticed that forgot to delete "Custom Location" Setting was configured before you provided me with the "Advanced term".

It's working like a charm now.

Just a normal host and the advance term you have mentioned and everything is working as expected now.

Thank you so much for your help! @jlesage
