### ISSUE TITLE
"exec format error"

### ISSUE THREAD

**Issue by LogicalUnit** [jlesage/docker-nginx-proxy-manager#82]
Hi there, I am trying to set up Nginx Proxy Manager with Portainer exactly as described in this YouTube video:
https://www.youtube.com/watch?v=z9pDPOrfhrs
The container is being created and starting, however I cannot access the interface on port 8181, and my Portainer logs just say:

standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",

I've done some Google searching, and there are a couple of places that say adding
#!/bin/bash to the top of the sh file can fix this problem

Would appreciate any help

**Comment by jlesage** [comment]
On which platform are you running the container ?  For now, only x86 is supported.

**Comment by LogicalUnit** [comment]
I'm running it on a Raspberry Pi 4 which is ARMv7. That would explain it. Is there an alternative you can point me to?

**Comment by fabiosoft** [comment]
Same issue for me... no ARM support? :(

**Comment by SelfhostedPro** [comment]
@jlesage do you want a PR to add arm support? I have an example here using github actions to build and automatically push to dockerhub: https://github.com/SelfhostedPro/Yacht/blob/master/.github/workflows/build.yml

**Comment by SelfhostedPro** [comment]
#119 is to build for multiarch using github actions.

**Comment by jlesage** [comment]
@SelfhostedPro thanks for the example.  I need to convert the actual build system (and all the associated workflow) not just for this particular container, but also for baseimages.  I already started to work on this, but the lack of time is slowing down things :)

**Comment by bluefangs** [comment]
Hi @jlesage - Wondering if there is any updates towards this. Would like to help in any way possible!
Thx

**Comment by my-flow** [comment]
+1

**Comment by jlesage** [comment]
The latest image is now multi-arch.
