### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by htogether** [jlesage/docker-nginx-proxy-manager#87]
my system is debian9 on my cloud mirror gen2.

docker dies with this error(standard_init_linux.go:211: exec user process caused "exec format error")

how do I remove this error?

**Comment by jlesage** [comment]
On which architecture are you running the container ?  Currently only x86_64 is supported.

**Comment by stopspazzing** [comment]
> my system is debian9 on my cloud mirror gen2.
> 
> docker dies with this error(standard_init_linux.go:211: exec user process caused "exec format error")
> 
> how do I remove this error?

Did that fix your error?

**Comment by GerritKuilder** [comment]
Hello,

Having the same issue, running on a raspberry p 4 ubuntu 64bit

Regards,

Gerrit Kuilder

**Comment by jlesage** [comment]
I'm working on adding support for more platforms, but currently only x86_64 is supported.

**Comment by GerritKuilder** [comment]
Thank you, there is this one lroguet/rpi-nginx-proxy that I am trying to use

**Comment by jlesage** [comment]
The latest image is now multi-arch.
