### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by scorpio2k2** [jlesage/docker-nginx-proxy-manager#88]
Hello,

After 2 days I cannot login. Is there an option to reset the password?

**Comment by jlesage** [comment]
Of course there is way: https://github.com/jlesage/docker-nginx-proxy-manager#password-reset

**Comment by scorpio2k2** [comment]
Hello,

The script is not present in the latest container image jc21/nginx-proxy-manager:2

**Comment by jlesage** [comment]
If you use the `jc21/nginx-proxy-manager` Docker image, then you should open an issue there: https://github.com/jc21/nginx-proxy-manager/issues
