### ISSUE TITLE
No resolver in config

### ISSUE THREAD

**Issue by RickoT** [jlesage/docker-nginx-proxy-manager#9]
The nginx config has no resolvers, this is important as the proxy will not resolve anything and I am required to now find a way that I can add that to my service build file every time the service restarts.  in the event something happens to the proxy container and it rebuilds (i.e. docker service restarts), i have to go back in and edit the /etc/nginx/nginx.conf file and add the 127.0.0.11 resolver again.

**Comment by jlesage** [comment]
Fixed in latest docker image.
