### ISSUE TITLE
ACL Not Working Properly - unRAID

### ISSUE THREAD

**Issue by joshmans** [jlesage/docker-nginx-proxy-manager#92]
Hello,

using unRAID - I can get certs fine - ports 80 and 443 are open and forwarded to the container.  Any proxy host I create tied to an access list returns 403 forbidden instead of prompting for a credential.  If I don't put it in an access list I can access no problem.

This issue is browser independent.

I have the container using user 99 and group 100 (nobody/nobody).  If I switch it to 0/0 (root) then I get a 'refused to connect'

Let me know if you need anything else to help troubleshoot.

Thank you!
Josh

**Comment by jlesage** [comment]
Can you please upgrade to the latest Docker image and do the following:

- In your access list, make sure `Satisfy All` is selected if you have set nothing under the `Access` tab.
- In your proxy, remove usage of the access list and save.
- Finally, re-enable usage of your access list in the proxy host and save.

**Comment by joshmans** [comment]
Greetings,

I upgraded to the latest image and now I can't load the Web UI at all.  Browser is giving a 'refused to connect' error.

**Comment by jlesage** [comment]
Could you provide the container's log ?

**Comment by jlesage** [comment]
Also, are your user/group still set to root ?  If yes, make sure to switch them back to their default value.

**Comment by joshmans** [comment]
[npm_log.txt](https://github.com/jlesage/docker-nginx-proxy-manager/files/4900468/npm_log.txt)

Log is attached.  Its from the point of starting the container... to stopping it once it starts scrolling 'nginx starting'

user/group is 99/100 respectively.

**Comment by jlesage** [comment]
Do you have anything in `/mnt/user/appdata/NginxProxyManager/log/error.log`?

**Comment by joshmans** [comment]
assuming you mean ...log/nginx/error.log -- no its blank.

**Comment by jlesage** [comment]
Don't you have both (/mnt/user/appdata/NginxProxyManager/log/error.log and /mnt/user/appdata/NginxProxyManager/log/nginx/error.log)?

Does the container stopped itself?  Make sure the container is running while looking at the files.  If they still appear empty, try to use `tail -f` instead (e.g. `tail -f /mnt/user/appdata/NginxProxyManager/log/nginx/error.log`).

**Comment by joshmans** [comment]
I stop the container manually so it doesn't constantly try to start nginx.. I let it go for the longest attempt 5 minutes.

I do not have an error.log under just log... i have an error.log only under nginx.

I have been checking while the container is running and tail doesn't give me anything either - just a blank line until I ctrl C.

Do you want me to delete and start with a fresh pull?

**Comment by jlesage** [comment]
If you don't mind re-doing your proxy host config, you can try to:

- Stop the container.
- Remove `/mnt/user/appdata/NginxProxyManager`.
- Start the container again.

This will start Nginx Proxy Manager from a clean state.

**Comment by joshmans** [comment]
Done. Same result with nginx just scrolling trying to start.

This error is still present in the docker log as well: Error: Command failed: /usr/sbin/nginx -t

**Comment by jlesage** [comment]
And still nothing in log files (you may look at all of them)?

Do you get the same problem if you execute:
```
docker run --rm jlesage/nginx-proxy-manager
```

**Comment by joshmans** [comment]
Same result and all log files are 0B / empty

**Comment by joshmans** [comment]
I do believe it is tied to this failure: `Error: Command failed: /usr/sbin/nginx -t`

But I don't know what is causing that since its not writing anything to the error.log file.  I did try to completely remove the container just now and do a fresh pull as well after cleaning up the appdata.  Same result.

**Comment by jlesage** [comment]
Can you try to login to the container (`docker exec -ti NginxProxyManager sh`) and execute:

```
s6-applyuidgid -u $USER_ID -g $GROUP_ID -G ${SUP_GROUP_IDS:-$GROUP_ID} /usr/sbin/nginx
```

**Comment by joshmans** [comment]
"Illegal Instruction" when trying to execute.

**Comment by jlesage** [comment]
What is the exact model of your CPU ?
```
cat /proc/cpuinfo
```

**Comment by joshmans** [comment]
I've got dual quad core Xeons:

vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 6
microcode       : 0x60f
cpu MHz         : 2021.058
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 6000.21
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

**Comment by jlesage** [comment]
The issue seems to be that your CPU doesn't support SSE 4.2:
http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E5450%20-%20EU80574KJ080N%20-%20AT80574KJ080N%20(BX80574E5450A).html

The latest container image is now using OpenResty, which uses SSE 4.2 (see https://github.com/openresty/openresty/issues/267).

I will check if it's possible to build it by explicitly disabling SSE 4.2.

**Comment by joshmans** [comment]
Bummer.  Thanks for checking into it. Let me know if you get it working that way. Or else I'll have to find another solution until I can upgrade my hardware.

**Comment by jlesage** [comment]
Please try the image that has just been pushed.  I hope it will work...

**Comment by joshmans** [comment]
Greetings,

It pulled, it starts now... but it is back to the original behavior of this issue and I followed these:

In your access list, make sure Satisfy All is selected if you have set nothing under the Access tab.
In your proxy, remove usage of the access list and save.
Finally, re-enable usage of your access list in the proxy host and save.

Thank You!

**Comment by jlesage** [comment]
Can you share the generated configuration for your proxy host that can be found under `/mnt/user/appdata/NginxProxyManager/nginx/proxy_host/` ?

**Comment by joshmans** [comment]
```
# ------------------------------------------------------------
# nzbg.jcmans.com
# ------------------------------------------------------------


server {
  set $forward_scheme http;
  set $server         "192.168.1.25";
  set $port           6788;

  listen 8080;
listen [::]:8080;

listen 4443 ssl http2;
listen [::]:4443;


  server_name nzbg.jcmans.com;


  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-1/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-1/privkey.pem;









  access_log /config/log/proxy_host-1.log proxy;







  location / {

    
    
    # Authorization
    auth_basic            "Authorization required";
    auth_basic_user_file  /data/access/1;
    

    # Access Rules
    deny all;

    # Access checks must...
    satisfy all;

    






    

    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

**Comment by jlesage** [comment]
Oh sorry, I meant that `Satisfy Any` should be selected, not `Satisfy All`.

**Comment by joshmans** [comment]
I did that, and now I get invalid cert.. it's presenting a localhost cert instead of the LE one.

**Comment by jlesage** [comment]
Ok and what is the generated config file in this case ?

**Comment by joshmans** [comment]
```
# ------------------------------------------------------------
# nzbg.jcmans.com
# ------------------------------------------------------------


server {
  set $forward_scheme http;
  set $server         "192.168.1.25";
  set $port           6788;

  listen 8080;
listen [::]:8080;


  server_name nzbg.jcmans.com;








  access_log /config/log/proxy_host-1.log proxy;







  location / {

    
    
    # Authorization
    auth_basic            "Authorization required";
    auth_basic_user_file  /data/access/1;
    

    # Access Rules
    deny all;

    # Access checks must...
    satisfy any;

    




    

    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}


```

**Comment by jlesage** [comment]
Ok, now at this point edit the proxy host and disable the access list (select `Publicly Available`) and save.  Then, edit again and select the access list.

After this, you should see in the generated config file the `Let's Encrypt SSL` block which is currently missing.  This should fix the certificate issue.

**Comment by joshmans** [comment]
Indeed it did, but now it's not taking the password I set in my access list. =/

**Comment by joshmans** [comment]
so it seems to be only on this one proxy host.  weird. I'll keep fighting it on my end - I think this issue can be considered resolved.
