### ISSUE TITLE
update broke my container

### ISSUE THREAD

**Issue by Jeeaaasus** [jlesage/docker-nginx-proxy-manager#93]
Container cannot start keeps saying:
> sed: can't move '/config/nginx/custom/server_proxy.confeOeegP' to '/config/nginx/custom/server_proxy.conf': Resource busy

then restarting 

> sed: can't move '/config/nginx/custom/server_proxy.confeLoOId' to '/config/nginx/custom/server_proxy.conf': Resource busy

and so on..

Container is working when I remove `-v /root/docker/backup/nginx/server_proxy.conf:/data/nginx/custom/server_proxy.conf` from my run cmd.

**Comment by jlesage** [comment]
Thanks for reporting.  This is fixed in the latest Docker image.

**Comment by Jeeaaasus** [comment]
Yeah works. Thank you very much!
