### ISSUE TITLE
nginx not working

### ISSUE THREAD

**Issue by nandurx** [jlesage/docker-nginx-proxy-manager#96]
I am complete beginner as I come from health care related background. I have posted all logs on this forum. Any help would be appreciated.

`https://forum.openmediavault.org/index.php?thread/33520-ngnix-proxy-manage-not-working/`

**Comment by jlesage** [comment]
First, your port forwards look strange... I'm not sure what is the meaning of each column.  On which device did you configured this ?  Also, you can use https://canyouseeme.org to verify that both ports 80 and 443 are accessible from the internet.  The errors returned by Nginx Proxy Manager seem to show that your server is not accessible from the Internet.

Then, you have Cloudflare setting showing that certificates are provided by Cloudflare. Does this apply to your configured CNAMEs ?  In other words, are your CNAMEs resolving to the IP address of your server or to an IP address of Cloudflare ?

**Comment by nandurx** [comment]
So port open checker does not show as open but if I check for my openvpn, it says port close but somehow I can still access open VPN from my cellphone so I don't know if those checker are really accurate.

Those port are configured on server ip. That's name assigned by router.

I don't understand this as I am complete beginner. Sorry.

`Then, you have Cloudflare setting showing that certificates are provided by Cloudflare. Does this apply to your configured CNAMEs ? In other words, are your CNAMEs resolving to the IP address of your server or to an IP address of Cloudflare ?`

I just followed DBTech tutorial to do this.

I really appreciate your reply.

**Comment by nandurx** [comment]
I think ssl provided by server:
![Screenshot_20200719-221510_Edge](https://user-images.githubusercontent.com/68475421/87893256-6076b780-ca0d-11ea-907a-3f3eb43a33f4.jpg)

**Comment by nandurx** [comment]
![20200719_221626](https://user-images.githubusercontent.com/68475421/87893358-a16ecc00-ca0d-11ea-9b2a-a1553712cb03.jpg)

**Comment by jlesage** [comment]
> So port open checker does not show as open but if I check for my openvpn, it says port close but somehow I can still access open VPN from my cellphone so I don't know if those checker are really accurate.

It's probably not working for openvpn because it usually runs on a UDP port.  The open port checker test TCP ports.

> Those port are configured on server ip. That's name assigned by router.

Sorry, it's still not clear for me where you configured port forwarding.  On your router ?

> I don't understand this as I am complete beginner. Sorry.

You can use https://mxtoolbox.com/DNSLookup.aspx to check your DNS names (e.g. ebook.example.com): do the `A` records point to the public IP of your server ?



> I just followed DBTech tutorial to do this.

Do you have a link to the tutorial?  This can help me understand what you did and what you are trying to do.

**Comment by nandurx** [comment]
Here is link to tutorial: https://youtu.be/bQdqf5xAyUk

Screenshot of clodflare:
![20200719_230420](https://user-images.githubusercontent.com/68475421/87895841-7b98f580-ca14-11ea-836e-19ff80e29d1b.jpg)


DNS server under domain manager are for cloudfare.

Port forwarded in router image 
![Screenshot_20200719-230908_Edge](https://user-images.githubusercontent.com/68475421/87895972-ecd8a880-ca14-11ea-8a68-ee47c3863e2f.jpg)
![Screenshot_20200719-230927_Edge](https://user-images.githubusercontent.com/68475421/87895978-f104c600-ca14-11ea-8bed-77ee0f409311.jpg)


 and for docker i have 8080 8181 and 4443 and I believe 8181 for webUI.

**Comment by nandurx** [comment]
I can see port is open as well.

**Comment by nandurx** [comment]
It started working. I had to do internal port forwarding that's why. Everything started working.
