### ISSUE TITLE
using an external mariadb database

### ISSUE THREAD

**Issue by a575606** [jlesage/docker-nginx-proxy-manager#99]
Hi,
Thanks for your work on polishing the NPM docker image. The built in database is a nice touch, however I was wondering if it's possible to use my existing mariadb instead? is it as simple as binding a new production.json file with different connection settings or will that create issues?

**Comment by jlesage** [comment]
I guess it could work.  But if you want to use your own DB, I would suggest to use the original project instead: https://github.com/jc21/nginx-proxy-manager

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
